export const es = {
  welcome_title: 'Programa Envejecimiento Activo',
  welcome_subtitle: 'Bienvenido a la aplicación de apoyo al estudio. Seleccione su idioma para comenzar.',
  select_language: 'Seleccionar Idioma',
  portuguese: 'Portugués (Brasil)',
  spanish: 'Español (España)',
  continue: 'Continuar',
  consent_title: 'Consentimiento Informado Electrónico',
  consent_intro: 'Por favor, lea el siguiente documento cuidadosamente. Su participación es voluntaria.',
  consent_item1_title: '1. Objetivo del Estudio',
  consent_item1_desc: 'El objetivo de este estudio es evaluar los efectos de un programa de ejercicios físicos en la salud y calidad de vida de los adultos mayores.',
  consent_item2_title: '2. Procedimientos',
  consent_item2_desc: 'Usted participará en sesiones de ejercicios físicos regulares y realizará evaluaciones físicas periódicas (fuerza, equilibrio, flexibilidad, etc.).',
  consent_item3_title: '3. Riesgos y Beneficios',
  consent_item3_desc: 'Los riesgos son mínimos y similares a los de la práctica regular de ejercicios físicos, como fatiga muscular leve. Los beneficios esperados incluyen mejoras en la capacidad funcional, fuerza y bienestar general.',
  consent_item4_title: '4. Confidencialidad y Voluntariedad',
  consent_item4_desc: 'Sus datos se mantendrán en absoluta confidencialidad y se utilizarán únicamente con fines de investigación. Su participación es totalmente voluntaria y puede retirarse en cualquier momento sin penalizaciones.',
  consent_accept: 'He leído y acepto participar',
  consent_decline: 'No acepto participar',
  screening_title: 'Cribado Clínico',
  screening_intro: 'Responda a las siguientes preguntas para garantizar su seguridad durante el estudio.',
  screening_q1: '¿Alguna vez un médico le ha dicho que tiene una afección cardíaca y que solo debe realizar actividad física recomendada por un médico?',
  screening_q2: '¿Siente dolor en el pecho cuando realiza actividad física?',
  screening_q3: 'En el último mes, ¿ha tenido dolor en el pecho cuando no estaba haciendo actividad física?',
  screening_q4: '¿Pierde el equilibrio por mareos o alguna vez pierde el conocimiento?',
  screening_q5: '¿Tiene algún problema óseo o articular (por ejemplo, espalda, rodilla o cadera) que podría empeorar con un aumento de la actividad física?',
  screening_submit: 'Enviar Respuestas',
  contact_professional: 'Basado en sus respuestas, por favor contacte a un profesional antes de continuar.',
  screening_success_title: 'Cribado Completado',
  screening_success_message: '¡Está listo para comenzar! Presione continuar para ir a su panel.',
  dashboard_participant_title: 'Mi Panel',
  dashboard_researcher_title: 'Panel del Investigador',
  next_session_title: 'Próxima Sesión de Entrenamiento',
  next_session_info: 'Sesión {sessionNumber}: {sessionType}',
  next_session_info_with_level: 'Sesión {sessionNumber}: {sessionType} - Nivel {level}',
  start_session: 'Iniciar Sesión',
  training_complete: '¡Felicitaciones! Ha completado su programa de entrenamiento.',
  sessions_completed: 'Sesiones Completadas',
  adherence_rate: 'Tasa de Adherencia',
  new_assessment: 'Nueva Evaluación',
  assessment_title: 'Registro de Evaluación',
  handgrip_strength: 'Fuerza de Prensión Manual (kgf)',
  balance: 'Equilibrio (s, apoyo unipodal)',
  flexibility: 'Flexibilidad (cm, Back-Scratch)',
  weight: 'Peso (kg)',
  height: 'Altura (cm)',
  calf_circumference: 'Circunferencia de Pantorrilla (cm)',
  bmi: 'Índice de Masa Corporal (IMC)',
  cc_bmi_index: 'Índice Alométrico (CC·IMC⁻¹)',
  save_assessment: 'Guardar Evaluación',
  assessment_saved_success: '¡Evaluación guardada con éxito!',
  session_title: 'Sesión de Entrenamiento: {sessionType}',
  complete_session: 'Completar Sesión',
  difficulty_feedback: '¿Cómo fue la sesión?',
  easy: 'Fácil',
  adequate: 'Adecuada',
  hard: 'Difícil',
  participant_view: 'Vista del Participante',
  researcher_view: 'Vista del Investigador',
  participants: 'Participantes',
  site_brazil: 'Sitio Brasil',
  site_spain: 'Sitio España',
  adherence_chart_title: 'Tasa de Adherencia por Semana',
  pre_post_chart_title: 'Comparación Pre vs. Post (Promedio)',
  select_participant: 'Seleccionar Participante',
  yes: 'Sí',
  no: 'No',
  my_assessments_title: 'Mis Evaluaciones',
  my_assessments_desc: 'Realice una nueva evaluación para seguir su progreso.',
  my_progress_title: 'Mi Progreso',
  no_assessments_yet: 'Las evaluaciones serán registradas por el investigador y aparecerán aquí.',
  back_button: 'Volver',
  continue_to_dashboard: 'Continuar al Panel',
  assessment_summary_title: 'Resumen de la Evaluación',
  assessment_summary_subtitle: 'Aquí están sus resultados. Su plan de entrenamiento se ajustará en función de ellos.',
  classification: 'Clasificación',
  classification_good: 'Bueno',
  classification_average: 'Promedio',
  classification_attention: 'Necesita Atención',
  duration_reps: '{count} reps',
  duration_reps_sets: '{count} reps × {sets} series',
  duration_seconds: '{count}s',
  duration_minutes: '{count} min',
  duration_seconds_per_leg: '{count}s por pierna',
  duration_seconds_per_arm: '{count}s por brazo',
  duration_steps: '{count} pasos',
  duration_per_side: '{count} por lado',
  session_type_strength: 'Fuerza',
  session_type_balance: 'Equilibrio',
  session_type_flexibility: 'Flexibilidad',
  session_type_cardio: 'Cardiorrespiratorio',
  session_type_posture: 'Postural',
  exercise_marching_in_place: 'Marcha en el sitio',
  exercise_arm_circles: 'Círculos con los brazos',
  exercise_sit_to_stand: 'Sentarse y levantarse',
  exercise_wall_push_ups: 'Flexiones en la pared',
  exercise_tandem_stance: 'Postura tándem',
  exercise_heel_raises: 'Elevación de talones',
  exercise_hamstring_stretch: 'Estiramiento de isquiotibiales',
  exercise_calf_stretch: 'Estiramiento de pantorrilla',
  exercise_step_ups: 'Subir escalón',
  exercise_bicep_curls: 'Curl de bíceps (con peso ligero)',
  exercise_lateral_leg_raises: 'Elevaciones laterales de pierna',
  exercise_single_leg_stance: 'Apoyo unipodal',
  exercise_heel_to_toe_walk: 'Caminar punta-talón',
  exercise_chair_yoga_poses: 'Posturas de yoga en silla',
  exercise_shoulder_stretch: 'Estiramiento de hombros',
  exercise_chest_stretch: 'Estiramiento de pecho',
  exercise_seated_rowing: 'Remo sentado (con banda elástica)',
  exercise_brisk_walking: 'Caminata rápida (en el sitio)',
  exercise_knee_highs: 'Elevación de rodillas',
  exercise_cat_cow_stretch: 'Estiramiento gato-vaca',
  exercise_bird_dog: 'Pájaro-perro',
  exercise_pelvic_tilt: 'Inclinación pélvica',
  safety_note_title: 'CONSEJO DE SEGURIDAD',
  instruction_sit_to_stand: 'Siéntese en una silla firme. Levántese hasta estar completamente de pie y vuelva a sentarse de forma controlada.',
  safety_sit_to_stand: 'Asegúrese de que la silla no se deslice. Mantenga las rodillas alineadas con los pies.',
  instruction_wall_push_ups: 'Párese frente a una pared, coloque las manos a la altura de los hombros. Doble los codos para acercar el pecho a la pared y empuje hacia atrás.',
  safety_wall_push_ups: 'Mantenga el cuerpo recto como una tabla. Use calzado antideslizante.',
  instruction_step_ups: 'Use un escalón firme. Suba con una pierna y baje de forma controlada. Alterne las piernas.',
  safety_step_ups: 'Tenga un apoyo cerca en caso de perder el equilibrio. El escalón debe ser estable.',
  instruction_bicep_curls: 'Sostenga un peso ligero en cada mano. Doble los codos para levantar los pesos hacia los hombros y baje lentamente.',
  safety_bicep_curls: 'Mantenga los codos cerca del cuerpo. No balancee el tronco.',
  instruction_lateral_leg_raises: 'De pie, sujétese a una silla. Levante una pierna hacia un lado sin inclinar el tronco y regrese.',
  safety_lateral_leg_raises: 'Mantenga la postura erguida. El movimiento debe ser lento y controlado.',
  instruction_heel_raises: 'De pie, apoyado en una silla, levante los talones poniéndose de puntillas y baje lentamente.',
  safety_heel_raises: 'Use el apoyo solo para mantener el equilibrio, no tire de la silla.',
  instruction_single_leg_stance: 'Párese sobre un pie, manteniendo el equilibrio. Use una silla como apoyo si es necesario.',
  safety_single_leg_stance: 'Manténgase cerca de una pared o silla firme para evitar caídas.',
  instruction_tandem_stance: 'Coloque un pie exactamente delante del otro (el talón tocando los dedos) y mantenga el equilibrio.',
  safety_tandem_stance: 'Realice el ejercicio cerca de una pared o apoyo.',
  instruction_heel_to_toe_walk: 'Camine en línea recta colocando el talón de un pie justo delante de los dedos del otro pie.',
  safety_heel_to_toe_walk: 'Mire hacia adelante, no hacia el suelo. Tenga una pared cerca.',
  instruction_arm_circles: 'Extienda los brazos hacia los lados y haga pequeños círculos hacia adelante y luego hacia atrás.',
  safety_arm_circles: 'Mantenga los hombros relajados, lejos de las orejas.',
  instruction_hamstring_stretch: 'Siéntese en el borde de una silla, estire una pierna con el talón en el suelo. Incline el tronco hacia adelante.',
  safety_hamstring_stretch: 'Mantenga la espalda recta. Vaya solo hasta sentir un estiramiento suave.',
  instruction_calf_stretch: 'Párese frente a una pared. Dé un paso atrás con una pierna, manteniendo el talón en el suelo y la rodilla estirada.',
  safety_calf_stretch: 'Mantenga los pies apuntando hacia adelante. No fuerce más allá del límite cómodo.',
  instruction_shoulder_stretch: 'Tire de un brazo a través del pecho usando la otra mano, estirando el hombro.',
  safety_shoulder_stretch: 'No tire de la articulación del codo, tire del brazo o antebrazo.',
  instruction_chest_stretch: 'Entrelace las manos detrás de la espalda y levante ligeramente los brazos para abrir el pecho.',
  safety_chest_stretch: 'Mantenga el cuello neutro. No fuerce los hombros.',
  instruction_brisk_walking: 'Camine a un ritmo rápido, pero que le permita mantener una conversación.',
  safety_brisk_walking: 'Use calzado cómodo y camine en un lugar plano y seguro.',
  instruction_marching_in_place: 'Marche en el mismo lugar, levantando las rodillas y moviendo los brazos.',
  safety_marching_in_place: 'Mantenga el abdomen contraído y la postura erguida.',
  instruction_knee_highs: 'De pie, levante una rodilla a la vez lo más alto que pueda de forma cómoda.',
  safety_knee_highs: 'Use una silla como apoyo si siente desequilibrio.',
  instruction_seated_rowing: 'Sentado, sostenga una banda elástica sujeta al frente. Tire de las manos hacia la cintura, apretando las escápulas.',
  safety_seated_rowing: 'Mantenga la columna recta. Verifique que la banda elástica esté bien sujeta.',
  instruction_cat_cow_stretch: 'En posición de cuatro patas, alterne entre curvar la espalda hacia arriba (gato) y hacia abajo (vaca).',
  safety_cat_cow_stretch: 'Haga movimientos suaves. Evite si tiene dolor en las muñecas o rodillas.',
  instruction_bird_dog: 'En posición de cuatro patas, extienda un brazo y la pierna opuesta simultáneamente. Alterne los lados.',
  safety_bird_dog: 'Mantenga el cuello alineado con la columna y el abdomen firme.',
  instruction_pelvic_tilt: 'Tumbado boca arriba, rodillas dobladas. Eleve la cadera del suelo hasta formar una línea recta desde las rodillas hasta los hombros.',
  safety_pelvic_tilt: 'Mantenga los pies firmes en el suelo y no fuerce el cuello.',
  series_label: 'SERIES',
  repetitions_label: 'REPETICIONES',
  duration_label: 'DURACIÓN',
  exit_session: 'Salir de la Sesión',
  belt_white: 'Cinturón Blanco',
  belt_yellow: 'Cinturón Amarillo',
  belt_orange: 'Cinturón Naranja',
  belt_green: 'Cinturón Verde',
  belt_blue: 'Cinturón Azul',
  belt_black: 'Cinturón Negro',
  current_belt: 'Tu Cinturón Actual',
  motivational_pre_session: '¡Vamos a fortalecer tu cuerpo hoy para garantizar más salud e independencia!',
  motivational_post_session: '¡Excelente trabajo! Cada sesión completada es un paso más hacia tu calidad de vida.',
  motivational_pre_1: '¡La consistencia es la clave! Vamos a por otro excelente entrenamiento.',
  motivational_pre_2: 'Tu cuerpo es tu hogar. Vamos a cuidarlo bien hoy.',
  motivational_pre_3: 'Recuerda: cada movimiento cuenta para tu independencia.',
  motivational_post_1: '¡Misión cumplida! Descansa bien, te lo has ganado.',
  motivational_post_2: '¡Increíble! Estás construyendo una versión más fuerte de ti mismo.',
  motivational_post_3: 'Un paso más hacia tus objetivos. ¡Felicidades por tu dedicación!',
  report_incident: 'Reportar Incidente',
  incident_title: 'Reporte de Seguridad',
  incident_desc: '¿Tuviste alguna caída, dolor inusual o mareo fuerte durante la última semana?',
  incident_yes: 'Sí, tuve un incidente',
  incident_no: 'No, todo estuvo bien',
  incident_reported: 'Gracias por reportarlo. Un investigador se pondrá en contacto pronto.',
  start_workout: 'Comenzar Entrenamiento',
  my_training_plan_title: 'Mi Plan de Entrenamiento',
  training_plan_not_generated: 'Plan de entrenamiento aún no generado. Aguarde la evaluación con el investigador.',
  training_plan_desc: 'Este es su plan de 8 semanas, personalizado en base a su evaluación.',
  day: 'Día',
  level: 'Nivel',
  completed: 'COMPLETADO',
  next_session: 'PRÓXIMA SESIÓN',
  exercise_x_of_y: 'Ejercicio {current} de {total}',
  previous: 'Anterior',
  next: 'Siguiente',
  program_not_found: 'Programa de entrenamiento no encontrado o participante inválido.',
  view_full_plan: 'Ver Plan Completo',
  select_metric: 'Seleccionar Métrica',
  percent_change: 'Cambio %',
  week: 'Semana',
  export_csv: 'Exportar a CSV',
  researcher_table_id: 'ID',
  researcher_table_site: 'Sitio',
  researcher_table_sessions: 'Sesiones',
  researcher_table_adherence: 'Adherencia',
  researcher_table_last_assessment: 'Últ. Evaluación',
  researcher_table_grip: 'Fuerza',
  researcher_table_balance: 'Equilibrio',
  researcher_table_flexibility: 'Flexibilidad',
  researcher_table_bmi: 'IMC',
  participant_name: 'Nombre',
  participant_sex: 'Sexo',
  participant_age: 'Edad',
  years_old: 'años',
  participant_dob: 'Fecha de Nacimiento',
  sex_m: 'Masculino',
  sex_f: 'Femenino',
  sex_other: 'Otro',
  happy_birthday: '¡Feliz Cumpleaños! 🎉',
  happy_birthday_msg: '¡Felicidades en tu día! Que este nuevo año de vida traiga aún más salud y vitalidad.',
  researcher_table_name: 'Nombre',
  researcher_table_sex: 'Sexo',
  researcher_table_age: 'Edad',
  confirm_end_session: '¿Desea finalizar la sesión actual y volver al inicio?',
  confirm_reset_all: 'ATENCIÓN: ¿Desea también BORRAR TODOS LOS DATOS (eliminar todos los participantes y evaluaciones) para reiniciar el programa desde cero?',
  login_subtitle: 'Acceda al programa con su código y contraseña.',
  login_access_code: 'Código de acceso',
  login_access_code_placeholder: 'Ej: ES-001',
  login_password: 'Contraseña',
  login_password_placeholder: 'DD/MM/AAAA',
  login_password_hint: 'Participantes: su fecha de nacimiento en formato DD/MM/AAAA.',
  login_submit: 'Entrar',
  login_error: 'Código o contraseña incorrectos. Verifique los datos e inténtelo de nuevo.',
  login_new_participant: '¿Todavía no tiene cuenta?',
  login_enroll_link: 'Iniciar registro como nuevo participante',
  awaiting_first_assessment: 'Su investigador realizará la evaluación física y a continuación se generará el plan de entrenamiento personalizado.',
  next_session_personalized_hint: 'Su plan de entrenamiento personalizado seleccionó esta sesión para centrarse en sus objetivos.',
  my_training_plan_desc: 'Vea la secuencia completa de 24 sesiones elaborada para usted.',
  back_to_dashboard: 'Volver al Panel',
  readonly_badge: 'Solo Lectura',
  new_participant: 'Nuevo Participante',
  view_participant_panel: 'Ver Panel',
  assessment_history_title: 'Historial de Evaluaciones',
  alerts_title: 'Alertas',
  alerts_subtitle: 'Incidentes reportados por los participantes durante las sesiones.',
  alerts_no_incidents: 'Ningún incidente reportado hasta el momento.',
  mark_reviewed: 'Marcar Resuelto',
  alert_reviewed: 'Resuelto',
  alert_pending: 'Pendiente',
  unreviewed_badge: '{count} pendiente(s)',
  alerts_col_participant: 'Participante',
  alerts_col_session: 'Sesión',
  alerts_col_date: 'Fecha',
  alerts_col_status: 'Estado',
  alerts_col_action: 'Acción',
  session_number_label: 'Sesión {number}',
  register_participant_title: 'Registro de Nuevo Participante',
  register_participant_intro: 'Complete los datos del participante. La fecha de nacimiento se usará como contraseña de acceso.',
  study_id_label: 'ID del Participante en el Estudio',
  study_id_hint: 'Si se deja en blanco, se generará un ID automáticamente.',
  site_label: 'Sede',
  birth_date_password_hint: 'Esta fecha se usará como contraseña de acceso del participante.',
  enrollment_save_and_return: 'Guardar y Volver al Panel',
  register_assessment: 'Registrar Evaluación',
  logout_button: 'Salir',
  // Bilingualism corrections — hardcoded strings moved to i18n
  participant_not_found: 'Participante no encontrado.',
  participant_session_expired: 'Participante no encontrado o sesión expirada.',
  back_to_start: 'Volver al Inicio',
  table_col_actions: 'Acciones',
  ready_to_start: '¿Listo para comenzar?',
  no_assessment_data: 'No se encontraron datos de evaluación.',
  click_session_hint: 'Haga clic en una sesión para ver los ejercicios.',
  level_abbr: 'Nv',
  full_name_placeholder: 'Nombre completo',
  // Alerts page
  alerts_col_occurrence: 'Ocurrencia',
  alerts_col_action_taken: 'Providencia',
  incident_occurrence_placeholder: 'Describa lo que ocurrió...',
  incident_action_placeholder: 'Describa la acción tomada...',
  // Metric group labels (dropdown)
  metric_group_body_comp: 'Composición Corporal',
  metric_group_strength: 'Fuerza y Función',
  metric_group_mobility: 'Movilidad',
  metric_group_aerobic: 'Capacidad Aeróbica',
  close_modal: 'Cerrar',
  session_modal_level: 'Nivel {level}',
  // Assessment stations
  assessment_station1: 'Estación 1 — Composición Corporal',
  assessment_station2: 'Estación 2 — Fuerza y Agilidad',
  assessment_station3: 'Estación 3 — Capacidad Aeróbica',
  waist_circumference: 'Circunferencia de Cintura (cm)',
  hip_circumference: 'Circunferencia de Cadera (cm)',
  body_fat_percent: 'Porcentaje de Grasa (%)',
  waist_hip_ratio: 'Relación Cintura-Cadera (RCC)',
  handgrip_dominant: 'Prensión — Mano Dominante (kgf)',
  handgrip_nondominant: 'Prensión — Mano No Dominante (kgf)',
  chair_stand_test: 'Sentarse y Levantarse (rep)',
  arm_curl_test: 'Curl de Bíceps (rep)',
  chair_sit_reach: 'Sentarse y Alcanzar (cm)',
  up_and_go: 'Levantarse y Caminar (s)',
  six_min_walk: 'TC6 — Caminata 6 Minutos (m)',
  six_min_walk_predicted: 'Distancia Prevista (m)',
  six_min_walk_percent: 'TC6 — Porcentaje de lo Previsto (%)',
  // Country labels (site field)
  country_brazil: 'Brasil',
  country_spain: 'España',
  // Table headers — TC6
  researcher_table_tc6: 'TC6 (m)',
  researcher_table_tc6_percent: 'TC6 — % Previsto',
  // Header modals
  home_tooltip: 'Inicio / Reiniciar',
  end_session_title: 'Cerrar Sesión',
  cancel: 'Cancelar',
  confirm_end_session_yes: 'Sí, cerrar',
  reset_data_title: 'Atención: Borrar Datos',
  reset_data_no: 'No, solo salir',
  reset_data_yes: 'Sí, borrar todo',
  login_loading: 'Cargando datos...',
  // Screening
  study_id_placeholder: 'Ej: ES-004',
  // Session history table (researcher view)
  session_history_title: 'Historial de Sesiones',
  session_history_col_session: 'Sesión',
  session_history_col_date: 'Fecha',
  session_history_col_start: 'Inicio',
  session_history_col_end: 'Fin',
  session_history_col_duration: 'Duración (min)',
  session_history_col_completed: 'Completada',
  session_history_completed_yes: 'Sí',
  session_history_completed_no: 'No',
};

export type I18nKeys = typeof es;