export const es = {
  welcome_title: 'Programa Envejecimiento Activo',
  welcome_subtitle: 'Bienvenido a la aplicación de apoyo al estudio. Seleccione su idioma para comenzar.',
  select_language: 'Seleccionar Idioma',
  portuguese: 'Portugués (Brasil)',
  spanish: 'Español (España)',
  continue: 'Continuar',
  consent_title: 'Consentimiento Informado Electrónico',
  consent_intro: 'Por favor, lea el siguiente documento cuidadosamente. Su participación es voluntaria.',
  consent_item1_title: '1. Objetivo del Estudio',
  consent_item1_desc: 'El objetivo de este estudio es evaluar los efectos de un programa de ejercicios físicos en la salud y calidad de vida de los adultos mayores.',
  consent_item2_title: '2. Procedimientos',
  consent_item2_desc: 'Usted participará en sesiones de ejercicios físicos regulares y realizará evaluaciones físicas periódicas (fuerza, equilibrio, flexibilidad, etc.).',
  consent_item3_title: '3. Riesgos y Beneficios',
  consent_item3_desc: 'Los riesgos son mínimos y similares a los de la práctica regular de ejercicios físicos, como fatiga muscular leve. Los beneficios esperados incluyen mejoras en la capacidad funcional, fuerza y bienestar general.',
  consent_item4_title: '4. Confidencialidad y Voluntariedad',
  consent_item4_desc: 'Sus datos se mantendrán en absoluta confidencialidad y se utilizarán únicamente con fines de investigación. Su participación es totalmente voluntaria y puede retirarse en cualquier momento sin penalizaciones.',
  consent_accept: 'He leído y acepto participar',
  consent_decline: 'No acepto participar',
  screening_title: 'Cribado Clínico',
  screening_intro: 'Responda a las siguientes preguntas para garantizar su seguridad durante el estudio.',
  screening_q1: '¿Alguna vez un médico le ha dicho que tiene una afección cardíaca y que solo debe realizar actividad física recomendada por un médico?',
  screening_q2: '¿Siente dolor en el pecho cuando realiza actividad física?',
  screening_q3: 'En el último mes, ¿ha tenido dolor en el pecho cuando no estaba haciendo actividad física?',
  screening_q4: '¿Pierde el equilibrio por mareos o alguna vez pierde el conocimiento?',
  screening_q5: '¿Tiene algún problema óseo o articular (por ejemplo, espalda, rodilla o cadera) que podría empeorar con un aumento de la actividad física?',
  screening_submit: 'Enviar Respuestas',
  contact_professional: 'Basado en sus respuestas, por favor contacte a un profesional antes de continuar.',
  screening_success_title: 'Cribado Completado',
  screening_success_message: '¡Está listo para comenzar! Presione continuar para ir a su panel.',
  dashboard_participant_title: 'Mi Panel',
  dashboard_researcher_title: 'Panel del Investigador',
  next_session_title: 'Próxima Sesión de Entrenamiento',
  next_session_info: 'Sesión {sessionNumber}: {sessionType}',
  next_session_info_with_level: 'Sesión {sessionNumber}: {sessionType} - Nivel {level}',
  start_session: 'Iniciar Sesión',
  training_complete: '¡Felicitaciones! Ha completado su programa de entrenamiento.',
  sessions_completed: 'Sesiones Completadas',
  adherence_rate: 'Tasa de Adherencia',
  new_assessment: 'Nueva Evaluación',
  assessment_title: 'Registro de Evaluación',
  handgrip_strength: 'Fuerza de Prensión Manual (kgf)',
  balance: 'Equilibrio (s, apoyo unipodal)',
  flexibility: 'Flexibilidad (cm, Back-Scratch)',
  weight: 'Peso (kg)',
  height: 'Altura (cm)',
  calf_circumference: 'Circunferencia de Pantorrilla (cm)',
  bmi: 'Índice de Masa Corporal (IMC)',
  cc_bmi_index: 'Índice Alométrico (CC·IMC⁻¹)',
  save_assessment: 'Guardar Evaluación',
  assessment_saved_success: '¡Evaluación guardada con éxito!',
  session_title: 'Sesión de Entrenamiento: {sessionType}',
  complete_session: 'Completar Sesión',
  wellness_question: '¿Cómo se sintió hoy?',
  difficulty_feedback: '¿Cómo fue la sesión?',
  easy: 'Fácil',
  adequate: 'Adecuada',
  hard: 'Difícil',
  participant_view: 'Vista del Participante',
  researcher_view: 'Vista del Investigador',
  participants: 'Participantes',
  site_brazil: 'Sitio Brasil',
  site_spain: 'Sitio España',
  adherence_chart_title: 'Tasa de Adherencia por Semana',
  pre_post_chart_title: 'Comparación Pre vs. Post (Promedio)',
  select_participant: 'Seleccionar Participante',
  yes: 'Sí',
  no: 'No',
  my_assessments_title: 'Mis Evaluaciones',
  my_assessments_desc: 'Realice una nueva evaluación para seguir su progreso.',
  my_progress_title: 'Mi Progreso',
  no_assessments_yet: 'Las evaluaciones serán registradas por el investigador y aparecerán aquí.',
  back_button: 'Volver',
  continue_to_dashboard: 'Continuar al Panel',
  assessment_summary_title: 'Resumen de la Evaluación',
  assessment_summary_subtitle: 'Aquí están sus resultados. Su plan de entrenamiento se ajustará en función de ellos.',
  classification: 'Clasificación',
  classification_good: 'Bueno',
  classification_average: 'Promedio',
  classification_attention: 'Necesita Atención',
  duration_reps: '{count} reps',
  duration_reps_sets: '{count} reps × {sets} series',
  duration_seconds: '{count}s',
  duration_minutes: '{count} min',
  duration_seconds_per_leg: '{count}s por pierna',
  duration_seconds_per_arm: '{count}s por brazo',
  duration_steps: '{count} pasos',
  duration_per_side: '{count} por lado',
  session_type_session1: 'Sesión A — Multicomponente',
  session_type_session2: 'Sesión B — Multicomponente',
  session_type_session3: 'Sesión C — Multicomponente',
  exercise_marching_in_place: 'Marcha en el sitio',
  exercise_arm_circles: 'Círculos con los brazos',
  exercise_sit_to_stand: 'Sentarse y levantarse',
  exercise_wall_push_ups: 'Flexiones en la pared',
  exercise_tandem_stance: 'Postura tándem',
  exercise_heel_raises: 'Elevación de talones',
  exercise_hamstring_stretch: 'Estiramiento de isquiotibiales',
  exercise_calf_stretch: 'Estiramiento de pantorrilla',
  exercise_step_ups: 'Subir escalón',
  exercise_bicep_curls: 'Curl de bíceps (con peso ligero)',
  exercise_lateral_leg_raises: 'Elevaciones laterales de pierna',
  exercise_single_leg_stance: 'Apoyo unipodal',
  exercise_heel_to_toe_walk: 'Caminar punta-talón',
  exercise_chair_yoga_poses: 'Posturas de yoga en silla',
  exercise_shoulder_stretch: 'Estiramiento de hombros',
  exercise_chest_stretch: 'Estiramiento de pecho',
  exercise_seated_rowing: 'Remo sentado (con banda elástica)',
  exercise_brisk_walking: 'Caminata rápida (en el sitio)',
  exercise_knee_highs: 'Elevación de rodillas',
  exercise_cat_cow_stretch: 'Estiramiento gato-vaca',
  exercise_bird_dog: 'Pájaro-perro',
  exercise_pelvic_tilt: 'Inclinación pélvica',
  safety_note_title: 'CONSEJO DE SEGURIDAD',
  instruction_sit_to_stand: 'Siéntese en una silla firme. Levántese hasta estar completamente de pie y vuelva a sentarse de forma controlada.',
  safety_sit_to_stand: 'Asegúrese de que la silla no se deslice. Mantenga las rodillas alineadas con los pies.',
  instruction_wall_push_ups: 'Párese frente a una pared, coloque las manos a la altura de los hombros. Doble los codos para acercar el pecho a la pared y empuje hacia atrás.',
  safety_wall_push_ups: 'Mantenga el cuerpo recto como una tabla. Use calzado antideslizante.',
  instruction_step_ups: 'Use un escalón firme. Suba con una pierna y baje de forma controlada. Alterne las piernas.',
  safety_step_ups: 'Tenga un apoyo cerca en caso de perder el equilibrio. El escalón debe ser estable.',
  instruction_bicep_curls: 'Sostenga un peso ligero en cada mano. Doble los codos para levantar los pesos hacia los hombros y baje lentamente.',
  safety_bicep_curls: 'Mantenga los codos cerca del cuerpo. No balancee el tronco.',
  instruction_lateral_leg_raises: 'De pie, sujétese a una silla. Levante una pierna hacia un lado sin inclinar el tronco y regrese.',
  safety_lateral_leg_raises: 'Mantenga la postura erguida. El movimiento debe ser lento y controlado.',
  instruction_heel_raises: 'De pie, apoyado en una silla, levante los talones poniéndose de puntillas y baje lentamente.',
  safety_heel_raises: 'Use el apoyo solo para mantener el equilibrio, no tire de la silla.',
  instruction_single_leg_stance: 'Párese sobre un pie, manteniendo el equilibrio. Use una silla como apoyo si es necesario.',
  safety_single_leg_stance: 'Manténgase cerca de una pared o silla firme para evitar caídas.',
  instruction_tandem_stance: 'Coloque un pie exactamente delante del otro (el talón tocando los dedos) y mantenga el equilibrio.',
  safety_tandem_stance: 'Realice el ejercicio cerca de una pared o apoyo.',
  instruction_heel_to_toe_walk: 'Camine en línea recta colocando el talón de un pie justo delante de los dedos del otro pie.',
  safety_heel_to_toe_walk: 'Mire hacia adelante, no hacia el suelo. Tenga una pared cerca.',
  instruction_arm_circles: 'Extienda los brazos hacia los lados y haga pequeños círculos hacia adelante y luego hacia atrás.',
  safety_arm_circles: 'Mantenga los hombros relajados, lejos de las orejas.',
  instruction_hamstring_stretch: 'Siéntese en el borde de una silla, estire una pierna con el talón en el suelo. Incline el tronco hacia adelante.',
  safety_hamstring_stretch: 'Mantenga la espalda recta. Vaya solo hasta sentir un estiramiento suave.',
  instruction_calf_stretch: 'Párese frente a una pared. Dé un paso atrás con una pierna, manteniendo el talón en el suelo y la rodilla estirada.',
  safety_calf_stretch: 'Mantenga los pies apuntando hacia adelante. No fuerce más allá del límite cómodo.',
  instruction_shoulder_stretch: 'Tire de un brazo a través del pecho usando la otra mano, estirando el hombro.',
  safety_shoulder_stretch: 'No tire de la articulación del codo, tire del brazo o antebrazo.',
  instruction_chest_stretch: 'Entrelace las manos detrás de la espalda y levante ligeramente los brazos para abrir el pecho.',
  safety_chest_stretch: 'Mantenga el cuello neutro. No fuerce los hombros.',
  instruction_brisk_walking: 'Camine a un ritmo rápido, pero que le permita mantener una conversación.',
  safety_brisk_walking: 'Use calzado cómodo y camine en un lugar plano y seguro.',
  instruction_marching_in_place: 'Marche en el mismo lugar, levantando las rodillas y moviendo los brazos.',
  safety_marching_in_place: 'Mantenga el abdomen contraído y la postura erguida.',
  instruction_knee_highs: 'De pie, levante una rodilla a la vez lo más alto que pueda de forma cómoda.',
  safety_knee_highs: 'Use una silla como apoyo si siente desequilibrio.',
  instruction_seated_rowing: 'Sentado, sostenga una banda elástica sujeta al frente. Tire de las manos hacia la cintura, apretando las escápulas.',
  safety_seated_rowing: 'Mantenga la columna recta. Verifique que la banda elástica esté bien sujeta.',
  instruction_cat_cow_stretch: 'En posición de cuatro patas, alterne entre curvar la espalda hacia arriba (gato) y hacia abajo (vaca).',
  safety_cat_cow_stretch: 'Haga movimientos suaves. Evite si tiene dolor en las muñecas o rodillas.',
  instruction_bird_dog: 'En posición de cuatro patas, extienda un brazo y la pierna opuesta simultáneamente. Alterne los lados.',
  safety_bird_dog: 'Mantenga el cuello alineado con la columna y el abdomen firme.',
  instruction_pelvic_tilt: 'Tumbado boca arriba, rodillas dobladas. Eleve la cadera del suelo hasta formar una línea recta desde las rodillas hasta los hombros.',
  safety_pelvic_tilt: 'Mantenga los pies firmes en el suelo y no fuerce el cuello.',
  warmup_phase_label: 'CALENTAMIENTO',
  warmup_phase_desc: 'Prepare su cuerpo con estos ejercicios antes de la actividad principal.',
  start_main_activity: 'Iniciar Actividad Principal',
  go_to_cooldown: 'Ir al Enfriamiento',
  cooldown_phase_label: 'VUELTA A LA CALMA',
  cooldown_phase_desc: 'Estire los músculos trabajados para recuperarse correctamente.',
  finish_cooldown: 'Finalizar Sesión',
  series_label: 'SERIES',
  repetitions_label: 'REPETICIONES',
  duration_label: 'DURACIÓN',
  exit_session: 'Salir de la Sesión',
  belt_white: 'Cinturón Blanco',
  belt_yellow: 'Cinturón Amarillo',
  belt_orange: 'Cinturón Naranja',
  belt_green: 'Cinturón Verde',
  belt_blue: 'Cinturón Azul',
  belt_black: 'Cinturón Negro',
  belt_progress_title: 'Progreso del Cinturón',
  belt_max_reached: '¡Felicidades! ¡Conquistaste el Cinturón Negro! 🏆',
  belt_sessions_progress: '{done} de {total} sesiones',
  belt_next_label: 'Próximo cinturón: {belt}',
  // ── Gestor del Sistema ─────────────────────────────────────────
  gestor_badge: 'Gestor del Sistema',
  researchers_section_title: 'Investigadores',
  researchers_add_button: '+ Añadir',
  researchers_cancel_button: '✕ Cancelar',
  researchers_code_label: 'Código de acceso *',
  researchers_code_placeholder: 'ej: PINERO',
  researchers_name_label: 'Nombre completo *',
  researchers_name_placeholder: 'ej: Josué Castro Piñero',
  researchers_password_label: 'Contraseña *',
  researchers_password_placeholder: 'Contraseña de acceso',
  researchers_site_label: 'Centro',
  researchers_site_all: 'Todos los centros',
  researchers_site_br: 'Brasil (BR)',
  researchers_site_es: 'España (ES)',
  researchers_save_button: 'Guardar Investigador',
  researchers_saving: '⏳ Guardando...',
  researchers_loading: 'Cargando...',
  researchers_empty: 'Ningún investigador registrado aún.',
  researchers_required_error: 'Código, nombre y contraseña son obligatorios.',
  researchers_col_code: 'Código',
  researchers_col_name: 'Nombre',
  researchers_col_site: 'Centro',
  researchers_col_created: 'Registrado el',
  researchers_col_status: 'Estado',
  researchers_col_action: 'Acción',
  researchers_status_active: 'Activo',
  researchers_status_inactive: 'Inactivo',
  researchers_deactivate: 'Desactivar',
  researchers_reactivate: 'Reactivar',
  delete_backup_note: 'Se generará un backup JSON automáticamente antes de la eliminación.',
  current_belt: 'Tu Cinturón Actual',
  motivational_pre_session: '¡Vamos a fortalecer tu cuerpo hoy para garantizar más salud e independencia!',
  motivational_post_session: '¡Excelente trabajo! Cada sesión completada es un paso más hacia tu calidad de vida.',
  motivational_pre_1: '¡La consistencia es la clave! Vamos a por otro excelente entrenamiento.',
  motivational_pre_2: 'Tu cuerpo es tu hogar. Vamos a cuidarlo bien hoy.',
  motivational_pre_3: 'Recuerda: cada movimiento cuenta para tu independencia.',
  motivational_post_1: '¡Misión cumplida! Descansa bien, te lo has ganado.',
  motivational_post_2: '¡Increíble! Estás construyendo una versión más fuerte de ti mismo.',
  motivational_post_3: 'Un paso más hacia tus objetivos. ¡Felicidades por tu dedicación!',
  report_incident: 'Reportar Incidente',
  incident_title: 'Reporte de Seguridad',
  incident_desc: '¿Tuviste alguna caída, dolor inusual o mareo fuerte durante la última semana?',
  incident_yes: 'Sí, tuve un incidente',
  incident_no: 'No, todo estuvo bien',
  incident_reported: 'Gracias por reportarlo. Un investigador se pondrá en contacto pronto.',
  start_workout: 'Comenzar Entrenamiento',
  my_training_plan_title: 'Mi Plan de Entrenamiento',
  training_plan_not_generated: 'Plan de entrenamiento aún no generado. Aguarde la evaluación con el investigador.',
  training_plan_desc: 'Este es su plan de 8 semanas, personalizado en base a su evaluación.',
  day: 'Día',
  level: 'Nivel',
  completed: 'COMPLETADO',
  next_session: 'PRÓXIMA SESIÓN',
  exercise_x_of_y: 'Ejercicio {current} de {total}',
  previous: 'Anterior',
  next: 'Siguiente',
  program_not_found: 'Programa de entrenamiento no encontrado o participante inválido.',
  view_full_plan: 'Ver Plan Completo',
  select_metric: 'Seleccionar Métrica',
  percent_change: 'Cambio %',
  week: 'Semana',
  export_csv: 'Exportar a CSV',
  researcher_table_id: 'ID',
  researcher_table_site: 'Sitio',
  researcher_table_sessions: 'Sesiones',
  researcher_table_adherence: 'Adherencia',
  researcher_table_last_assessment: 'Últ. Evaluación',
  researcher_table_grip: 'Fuerza',
  researcher_table_balance: 'Equilibrio',
  researcher_table_flexibility: 'Flexibilidad',
  researcher_table_bmi: 'IMC',
  participant_name: 'Nombre',
  participant_sex: 'Sexo',
  participant_age: 'Edad',
  years_old: 'años',
  participant_dob: 'Fecha de Nacimiento',
  sex_m: 'Masculino',
  sex_f: 'Femenino',
  sex_other: 'Otro',
  happy_birthday: '¡Feliz Cumpleaños! 🎉',
  happy_birthday_msg: '¡Felicidades en tu día! Que este nuevo año de vida traiga aún más salud y vitalidad.',
  researcher_table_name: 'Nombre',
  researcher_table_sex: 'Sexo',
  researcher_table_age: 'Edad',
  confirm_end_session: '¿Desea finalizar la sesión actual y volver al inicio?',
  confirm_reset_all: 'Esta acción eliminará permanentemente todos los participantes y evaluaciones. No se puede deshacer.',
  login_subtitle: 'Acceda al programa con su código y contraseña.',
  login_access_code: 'Código de acceso',
  login_access_code_placeholder: 'Ej: ES-001',
  login_password: 'Contraseña',
  login_password_placeholder: '19570618',
  login_password_hint: 'Ingrese su fecha de nacimiento en formato AAAAMMDD (ej: 19570618)',
  login_submit: 'Entrar',
  login_error: 'Código o contraseña incorrectos. Verifique los datos e inténtelo de nuevo.',
  login_new_participant: '¿Todavía no tiene cuenta?',
  login_enroll_link: 'Iniciar registro como nuevo participante',
  awaiting_first_assessment: 'Su investigador realizará la evaluación física y a continuación se generará el plan de entrenamiento personalizado.',
  next_session_personalized_hint: 'Su plan de entrenamiento personalizado seleccionó esta sesión para centrarse en sus objetivos.',
  my_training_plan_desc: 'Vea la secuencia completa de 24 sesiones elaborada para usted.',
  back_to_dashboard: 'Volver al Panel',
  readonly_badge: 'Solo Lectura',
  new_participant: 'Nuevo Participante',
  view_participant_panel: 'Ver Panel',
  assessment_history_title: 'Historial de Evaluaciones',
  alerts_title: 'Alertas',
  alerts_subtitle: 'Incidentes reportados por los participantes durante las sesiones.',
  alerts_no_incidents: 'Ningún incidente reportado hasta el momento.',
  mark_reviewed: 'Marcar Resuelto',
  alert_reviewed: 'Resuelto',
  alert_pending: 'Pendiente',
  unreviewed_badge: '{count} pendiente(s)',
  alerts_col_participant: 'Participante',
  alerts_col_session: 'Sesión',
  alerts_col_date: 'Fecha',
  alerts_col_status: 'Estado',
  alerts_col_action: 'Acción',
  session_number_label: 'Sesión {number}',
  register_participant_title: 'Registro de Nuevo Participante',
  register_participant_intro: 'Complete los datos del participante. La fecha de nacimiento se usará como contraseña de acceso.',
  study_id_label: 'ID del Participante en el Estudio',
  study_id_hint: 'Si se deja en blanco, se generará un ID automáticamente.',
  study_id_auto_hint: 'Generado automáticamente',
  site_label: 'Sede',
  birth_date_password_hint: 'Esta fecha se usará como contraseña de acceso del participante.',
  enrollment_save_and_return: 'Guardar y Volver al Panel',
  register_assessment: 'Registrar Evaluación',
  logout_button: 'Salir',
  // Bilingualism corrections — hardcoded strings moved to i18n
  participant_not_found: 'Participante no encontrado.',
  participant_session_expired: 'Participante no encontrado o sesión expirada.',
  back_to_start: 'Volver al Inicio',
  table_col_actions: 'Acciones',
  ready_to_start: '¿Listo para comenzar?',
  no_assessment_data: 'No se encontraron datos de evaluación.',
  click_session_hint: 'Haga clic en una sesión para ver los ejercicios.',
  level_abbr: 'Nv',
  full_name_placeholder: 'Nombre completo',
  // Alerts page
  alerts_col_occurrence: 'Ocurrencia',
  alerts_col_action_taken: 'Providencia',
  incident_occurrence_placeholder: 'Describa lo que ocurrió...',
  incident_action_placeholder: 'Describa la acción tomada...',
  // Metric group labels (dropdown)
  metric_group_body_comp: 'Composición Corporal',
  metric_group_strength: 'Fuerza y Función',
  metric_group_mobility: 'Movilidad',
  metric_group_aerobic: 'Capacidad Aeróbica',
  close_modal: 'Cerrar',
  session_modal_level: 'Nivel {level}',
  // Assessment stations
  assessment_station1: 'Estación 1 — Composición Corporal',
  assessment_station2: 'Estación 2 — Fuerza y Agilidad',
  assessment_station3: 'Estación 3 — Capacidad Aeróbica',
  waist_circumference: 'Circunferencia de Cintura (cm)',
  hip_circumference: 'Circunferencia de Cadera (cm)',
  body_fat_percent: 'Porcentaje de Grasa (%)',
  waist_hip_ratio: 'Relación Cintura-Cadera (RCC)',
  handgrip_dominant: 'Prensión — Mano Dominante (kgf)',
  handgrip_nondominant: 'Prensión — Mano No Dominante (kgf)',
  chair_stand_test: 'Sentarse y Levantarse (rep)',
  arm_curl_test: 'Curl de Bíceps (rep)',
  chair_sit_reach: 'Sentarse y Alcanzar (cm)',
  up_and_go: 'Levantarse y Caminar (s)',
  six_min_walk: 'TC6 — Caminata 6 Minutos (m)',
  six_min_walk_predicted: 'Distancia Prevista (m)',
  six_min_walk_percent: 'TC6 — Porcentaje de lo Previsto (%)',
  // Country labels (site field)
  country_brazil: 'Brasil',
  country_spain: 'España',
  // Table headers — TC6
  researcher_table_tc6: 'TC6 (m)',
  researcher_table_tc6_percent: 'TC6 — % Previsto',
  // Header modals
  home_tooltip: 'Inicio / Reiniciar',
  end_session_title: 'Cerrar Sesión',
  cancel: 'Cancelar',
  confirm_end_session_yes: 'Sí, cerrar',
  reset_data_title: 'Atención: Borrar Datos',
  reset_data_no: 'No, solo salir',
  reset_data_yes: 'Borrar Todos los Datos',
  login_loading: 'Cargando datos...',
  login_connection_error: 'No se pudo conectar al servidor. Verifique su conexión e inténtelo de nuevo.',
  // Screening
  study_id_placeholder: 'Ej: ES-004',
  // Session history table (researcher view)
  session_history_title: 'Historial de Sesiones',
  session_history_col_session: 'Sesión',
  session_history_col_date: 'Fecha',
  session_history_col_start: 'Inicio',
  session_history_col_end: 'Fin',
  session_history_col_duration: 'Duración (min)',
  session_history_col_completed: 'Completada',
  session_history_completed_yes: 'Sí',
  session_history_completed_no: 'No',
  // RPE por ejercicio (Asier Fase 1)
  rpe_zone_label: 'Esfuerzo esperado',
  load_rec_label: 'Carga sugerida',
  rpe_talk_test: 'Debes ser capaz de mantener una conversación breve durante el ejercicio',
  rpe_picker_title: '¿Cómo fue el esfuerzo en este ejercicio?',
  rpe_light: '🟢 Leve',
  rpe_moderate: '🟡 Moderado',
  rpe_hard: '🔴 Intenso',
  rpe_light_desc: 'RPE ≤ 4 — Muy fácil',
  rpe_moderate_desc: 'RPE 5–6 — En la zona ideal',
  rpe_hard_desc: 'RPE ≥ 7 — Demasiado difícil',
  // ── Nuevos ejercicios de calentamiento (AQ-01 a AQ-09) ───────────────────
  exercise_ankle_circles: 'Círculos de tobillo',
  exercise_knee_flexion_extension: 'Flexión-extensión de rodilla (sentado)',
  exercise_hip_circles: 'Círculos de cadera',
  exercise_shoulder_circles: 'Círculos de hombro',
  exercise_wrist_circles: 'Círculos de muñeca',
  exercise_neck_mobility: 'Movilidad de cuello',
  exercise_diagonal_foot_taps: 'Toques diagonales de pie',
  exercise_lateral_steps: 'Pasos laterales',
  exercise_v_step: 'Paso en V',
  instruction_ankle_circles: 'Sentado o de pie con apoyo, levanta ligeramente un pie del suelo y haz círculos con el tobillo, primero hacia un lado y luego hacia el otro. Alterna los pies.',
  instruction_knee_flexion_extension: 'Sentado en una silla, estira lentamente una pierna hasta casi extenderla del todo y vuélvela a doblar. Alterna las piernas.',
  instruction_hip_circles: 'De pie, con los pies separados a la anchura de los hombros y las manos en las caderas, haz círculos amplios con la cadera en sentido horario y luego antihorario.',
  instruction_shoulder_circles: 'Sentado o de pie, eleva los hombros hacia las orejas, gíralos hacia atrás, hacia abajo y hacia adelante. Luego invierte el sentido.',
  instruction_wrist_circles: 'Extiende los brazos al frente con las manos abiertas. Haz círculos lentos con las muñecas hacia un lado y luego hacia el otro.',
  instruction_neck_mobility: 'Sentado con la columna erguida, inclina lentamente la cabeza hacia un lado (oreja hacia el hombro), vuelve al centro y repite hacia el otro lado. Luego gira suavemente la cabeza de un lado al otro.',
  instruction_diagonal_foot_taps: 'De pie, apoyado en una silla, toca con el pie derecho en diagonal frontal derecha, luego lateral y luego diagonal posterior. Repite con el pie izquierdo.',
  instruction_lateral_steps: 'De pie, da dos pasos hacia la derecha y luego dos hacia la izquierda, manteniendo las rodillas ligeramente flexionadas y el tronco erguido.',
  instruction_v_step: 'Comienza con los pies juntos. Abre los pies hacia los lados (formando una V) y luego únelos de nuevo al centro. Mantén un ritmo constante.',
  safety_ankle_circles: 'Realiza movimientos suaves. Si estás de pie, usa apoyo para no perder el equilibrio.',
  safety_knee_flexion_extension: 'Movimiento lento y controlado. No fuerces más allá del confort, especialmente si hay dolor de rodilla.',
  safety_hip_circles: 'Apóyate en una silla si sientes desequilibrio. No fuerces más allá del ángulo cómodo.',
  safety_shoulder_circles: 'Movimientos lentos y suaves. Detente si sientes dolor o chasquido en el hombro.',
  safety_wrist_circles: 'Movimientos suaves. Detente si sientes dolor o entumecimiento en las muñecas.',
  safety_neck_mobility: 'Nunca inclines la cabeza completamente hacia atrás. Todos los movimientos deben ser muy lentos y controlados.',
  safety_diagonal_foot_taps: 'Sujétate firmemente a la silla. No avances el toque más allá del equilibrio cómodo.',
  safety_lateral_steps: 'Usa calzado antideslizante. Comprueba el espacio alrededor antes de empezar.',
  safety_v_step: 'Comienza al ritmo más lento. Usa apoyo si es necesario.',
  // ── Nuevos ejercicios de vuelta a la calma (DQ-01 a DQ-04) ───────────────
  exercise_glute_stretch: 'Estiramiento de glúteos',
  exercise_quad_stretch: 'Estiramiento de cuádriceps',
  exercise_back_stretch: 'Estiramiento de espalda',
  exercise_neck_adductor_stretch: 'Estiramiento de cuello y aductores',
  instruction_glute_stretch: 'Tumbado boca arriba, cruza el tobillo derecho sobre la rodilla izquierda flexionada. Tira suavemente del muslo izquierdo hacia el pecho. Mantén y cambia de lado.',
  instruction_quad_stretch: 'De pie, apoyado en una silla, dobla la rodilla derecha llevando el talón hacia el glúteo y sujeta el pie con la mano derecha. Mantén y cambia de lado.',
  instruction_back_stretch: 'Sentado, redondea ligeramente la espalda inclinando el tronco hacia adelante, abrazando las propias rodillas o estirando los brazos al frente. Mantén la posición.',
  instruction_neck_adductor_stretch: 'Sentado en el borde de la silla con las piernas abiertas, inclina el tronco hacia adelante estirando los aductores. Para el cuello: inclina la cabeza hacia un lado con leve ayuda de la mano opuesta.',
  safety_glute_stretch: 'Mantén la espalda apoyada en el suelo. No fuerces la cadera más allá de lo cómodo.',
  safety_quad_stretch: 'Mantente erguido y firme en el apoyo. No tires de la rodilla más allá del ángulo cómodo.',
  safety_back_stretch: 'Movimientos suaves. Evitar si hay hernia discal o dolor intenso de espalda.',
  safety_neck_adductor_stretch: 'Movimientos muy suaves. No fuerces el cuello. Detente si sientes dolor.',
  // Final reset confirmation modal
  reset_final_title: 'Confirmación Final — Acción Irreversible',
  reset_final_warning: 'ATENCIÓN: Esta acción eliminará TODOS los participantes y evaluaciones de Supabase y no se puede deshacer.',
  reset_final_type_hint: 'Escriba CONFIRMAR para habilitar el botón de eliminación:',
  reset_final_button: 'Borrar Todo y Reiniciar',

  // ── PP ejercicios existentes sin i18n ────────────────────────────────────
  exercise_skipping: 'Simulación de saltar cuerda',
  instruction_skipping: 'De pie, simula saltar una cuerda imaginaria: salta levemente sobre los pies alternando o en conjunto, moviendo los brazos en círculo a los lados del cuerpo. Mantén un ritmo constante.',
  safety_skipping: 'Usa calzado con amortiguación. Reduce la altura del salto o realiza solo el movimiento de brazos si sientes molestias en las articulaciones.',

  exercise_sumo_deadlift_band: 'Peso muerto sumo con banda',
  instruction_sumo_deadlift_band: 'De pie con los pies más separados que los hombros y las puntas hacia afuera. Pisa la banda elástica y sujeta los extremos. Dobla las rodillas y las caderas para bajar, luego extiende para volver a ponerte de pie apretando los glúteos en la parte superior.',
  safety_sumo_deadlift_band: 'Mantén la espalda recta y el pecho erguido durante todo el movimiento. No redondees la zona lumbar.',

  exercise_dead_bug: 'Cucaracha muerta (Dead Bug)',
  instruction_dead_bug: 'Tumbado boca arriba con brazos extendidos hacia el techo y rodillas dobladas a 90°. Baja lentamente un brazo hacia atrás y la pierna opuesta hacia el suelo sin tocarlos. Vuelve al centro. Alterna los lados.',
  safety_dead_bug: 'Mantén la zona lumbar apoyada en el suelo durante todo el movimiento. Respira de forma controlada.',

  // ── PP nuevos ejercicios (Sesiones A/B/C) ────────────────────────────────
  exercise_lunge: 'Zancada (Lunge)',
  instruction_lunge: 'De pie, da un paso largo hacia adelante con el pie derecho. Baja la rodilla trasera hacia el suelo hasta que ambas rodillas formen ~90°. Vuelve a la posición inicial. Alterna las piernas.',
  safety_lunge: 'Usa una silla como apoyo lateral si necesitas equilibrio. La rodilla delantera no debe sobrepasar la punta del pie.',

  exercise_hip_abduction_band: 'Abducción de cadera con banda',
  instruction_hip_abduction_band: 'De pie, apoyado en una silla, con la banda elástica alrededor de los tobillos. Eleva lateralmente una pierna alejándola del cuerpo, manteniendo el tronco erguido. Vuelve lentamente. Alterna las piernas.',
  safety_hip_abduction_band: 'Mantente firme en el apoyo. No eleves la pierna más allá de lo que el equilibrio te permita.',

  exercise_glute_bridge_band: 'Puente de glúteos con banda',
  instruction_glute_bridge_band: 'Tumbado boca arriba con rodillas dobladas y la banda elástica por encima de las rodillas. Empuja las rodillas hacia afuera y eleva la cadera del suelo formando una línea recta desde los hombros hasta las rodillas. Baja lentamente.',
  safety_glute_bridge_band: 'Mantén los pies bien apoyados en el suelo. No arquees excesivamente la zona lumbar.',

  exercise_rowing_with_resistance_band: 'Remada con banda elástica',
  instruction_rowing_with_resistance_band: 'De pie o sentado, sujeta los extremos de la banda elástica anclada al frente a la altura del pecho. Tira de los codos hacia atrás apretando las escápulas. Vuelve lentamente a la posición inicial.',
  safety_rowing_with_resistance_band: 'Mantén la espalda recta durante todo el movimiento. Verifica que la banda esté bien anclada antes de comenzar.',

  exercise_scapular_retraction_band: 'Retracción escapular con banda',
  instruction_scapular_retraction_band: 'De pie, sujeta la banda elástica por ambos extremos con los brazos extendidos al frente. Tira de los brazos hacia los lados apretando las escápulas. Mantén los codos ligeramente doblados.',
  safety_scapular_retraction_band: 'Movimiento lento y controlado. Mantén los hombros alejados de las orejas.',

  exercise_tricep_extension_band: 'Extensión de tríceps con banda',
  instruction_tricep_extension_band: 'De pie, pisa la banda con un pie. Sujeta el extremo libre y lleva el codo hacia arriba (doblado junto a la cabeza). Extiende el brazo hacia arriba estirando el tríceps. Vuelve lentamente. Alterna los brazos.',
  safety_tricep_extension_band: 'Mantén el codo apuntando al techo durante el movimiento. Usa una tensión de banda adecuada.',

  exercise_floor_push_ups: 'Flexión en el suelo',
  instruction_floor_push_ups: 'En posición de plancha, con las manos apoyadas en el suelo a la anchura de los hombros, baja el pecho hacia el suelo doblando los codos. Empuja hacia arriba para volver. Se puede hacer con rodillas apoyadas si es necesario.',
  safety_floor_push_ups: 'Mantén el cuerpo alineado de cabeza a talones (o rodillas). No bloquees los codos al extender.',

  exercise_front_plank: 'Plancha frontal',
  instruction_front_plank: 'Apoya los antebrazos y las puntas de los pies en el suelo. Mantén el cuerpo en línea recta de cabeza a talones con el abdomen contraído. Respira con normalidad mientras mantienes la posición.',
  safety_front_plank: 'Si es demasiado difícil, apoya las rodillas. No dejes caer las caderas ni las eleves demasiado.',

  exercise_side_plank_knee: 'Plancha lateral (rodilla apoyada)',
  instruction_side_plank_knee: 'Tumbado de lado, apoya el antebrazo en el suelo y la rodilla inferior doblada como apoyo. Eleva la cadera formando una línea recta desde la rodilla hasta el hombro. Mantén la posición. Cambia de lado.',
  safety_side_plank_knee: 'Alinea el codo bajo el hombro. Mantén el abdomen contraído y respira con normalidad.',

  exercise_slow_mountain_climber: 'Escalador lento',
  instruction_slow_mountain_climber: 'En posición de plancha alta (manos en el suelo), lleva lentamente una rodilla hacia el pecho y vuelve a extenderla. Alterna las piernas de forma controlada, sin elevar las caderas.',
  safety_slow_mountain_climber: 'Mantén la espalda recta y el abdomen contraído. Muévete lentamente para no perder el equilibrio.',

  exercise_foot_taps_directions: 'Toques en múltiples direcciones',
  instruction_foot_taps_directions: 'Apoyado en una silla, toca con el pie derecho en diferentes direcciones: adelante, lateral y atrás. Luego repite con el pie izquierdo. Mantén el equilibrio sobre el pie de apoyo.',
  safety_foot_taps_directions: 'Sujétate bien a la silla. Empieza con amplitudes pequeñas y auméntalas progresivamente.',

  exercise_lateral_shuffle: 'Desplazamiento lateral',
  instruction_lateral_shuffle: 'Con las rodillas ligeramente dobladas y el tronco levemente inclinado hacia adelante, da pasos rápidos hacia la derecha y luego hacia la izquierda, arrastrando el pie trasero antes del siguiente paso.',
  safety_lateral_shuffle: 'Despeja el espacio de obstáculos. Usa calzado antideslizante. Reduce la velocidad si sientes inestabilidad.',

  exercise_step_touch: 'Toque lateral (Step Touch)',
  instruction_step_touch: 'Da un paso hacia la derecha con el pie derecho y luego toca el suelo con el pie izquierdo a su lado. Repite hacia la izquierda. Mantén un ritmo constante y mueve los brazos de forma sincronizada.',
  safety_step_touch: 'Comprueba el espacio a los lados. Reduce la amplitud del paso si sientes desequilibrio.',
};

export type I18nKeys = typeof es;