import { I18nKeys } from './es';

export const pt: I18nKeys = {
  welcome_title: 'Programa Envelhecimento Ativo',
  welcome_subtitle: 'Bem-vindo ao aplicativo de apoio ao estudo. Selecione seu idioma para começar.',
  select_language: 'Selecionar Idioma',
  portuguese: 'Português (Brasil)',
  spanish: 'Espanhol (Espanha)',
  continue: 'Continuar',
  consent_title: 'Termo de Consentimento Livre e Esclarecido',
  consent_intro: 'Por favor, leia o documento a seguir com atenção. Sua participação é voluntária.',
  consent_item1_title: '1. Objetivo do Estudo',
  consent_item1_desc: 'O objetivo deste estudo é avaliar os efeitos de um programa de exercícios físicos na saúde e qualidade de vida de idosos.',
  consent_item2_title: '2. Procedimentos',
  consent_item2_desc: 'Você participará de sessões de exercícios físicos regulares e realizará avaliações físicas periódicas (força, equilíbrio, flexibilidade, etc.).',
  consent_item3_title: '3. Riscos e Benefícios',
  consent_item3_desc: 'Os riscos são mínimos e semelhantes aos da prática regular de exercícios físicos, como fadiga muscular leve. Os benefícios esperados incluem melhora na capacidade funcional, força e bem-estar geral.',
  consent_item4_title: '4. Confidencialidade e Voluntariedade',
  consent_item4_desc: 'Seus dados serão mantidos em sigilo absoluto e usados apenas para fins de pesquisa. Sua participação é totalmente voluntária, podendo você desistir a qualquer momento sem penalidades.',
  consent_accept: 'Li e aceito participar',
  consent_decline: 'Não aceito participar',
  screening_title: 'Triagem Clínica',
  screening_intro: 'Responda às seguintes perguntas para garantir sua segurança durante o estudo.',
  screening_q1: 'Algum médico já lhe disse que você tem um problema de coração e que só deveria realizar atividade física supervisionado por profissionais de saúde?',
  screening_q2: 'Você sente dor no peito ao fazer atividade física?',
  screening_q3: 'No último mês, você sentiu dor no peito quando não estava fazendo atividade física?',
  screening_q4: 'Você perde o equilíbrio por tontura ou alguma vez perdeu a consciência?',
  screening_q5: 'Você tem algum problema ósseo ou articular (por exemplo, nas costas, joelho ou quadril) que poderia ser agravado pela atividade física?',
  screening_submit: 'Enviar Respostas',
  contact_professional: 'Com base em suas respostas, por favor, contate um profissional antes de continuar.',
  screening_success_title: 'Triagem Concluída',
  screening_success_message: 'Você está pronto para começar! Pressione continuar para ir ao seu painel.',
  dashboard_participant_title: 'Meu Painel',
  dashboard_researcher_title: 'Painel do Pesquisador',
  next_session_title: 'Próxima Sessão de Treino',
  next_session_info: 'Sessão {sessionNumber}: {sessionType}',
  next_session_info_with_level: 'Sessão {sessionNumber}: {sessionType} - Nível {level}',
  start_session: 'Iniciar Sessão',
  training_complete: 'Parabéns! Você completou seu programa de treino.',
  sessions_completed: 'Sessões Concluídas',
  adherence_rate: 'Taxa de Adesão',
  new_assessment: 'Nova Avaliação',
  assessment_title: 'Registro de Avaliação',
  handgrip_strength: 'Força de Preensão Manual (kgf)',
  balance: 'Equilíbrio (s, apoio unipodal)',
  flexibility: 'Flexibilidade (cm, Teste de Tocar as Mãos nas Costas)',
  weight: 'Peso (kg)',
  height: 'Altura (cm)',
  calf_circumference: 'Circunferência da Panturrilha (cm)',
  bmi: 'Índice de Massa Corporal (IMC)',
  cc_bmi_index: 'Índice Alométrico (CP·IMC⁻¹)',
  save_assessment: 'Salvar Avaliação',
  assessment_saved_success: 'Avaliação salva com sucesso!',
  session_title: 'Sessão de Treino: {sessionType}',
  complete_session: 'Concluir Sessão',
  difficulty_feedback: 'Como foi a sessão?',
  easy: 'Fácil',
  adequate: 'Adequada',
  hard: 'Difícil',
  participant_view: 'Visão do Participante',
  researcher_view: 'Visão do Pesquisador',
  participants: 'Participantes',
  site_brazil: 'Polo Brasil',
  site_spain: 'Polo Espanha',
  adherence_chart_title: 'Taxa de Adesão por Semana',
  pre_post_chart_title: 'Comparativo Pré vs. Pós (Média)',
  select_participant: 'Selecionar Participante',
  yes: 'Sim',
  no: 'Não',
  my_assessments_title: 'Minhas Avaliações',
  my_assessments_desc: 'Realize uma nova avaliação para acompanhar seu progresso.',
  my_progress_title: 'Meu Progresso',
  no_assessments_yet: 'As avaliações serão registradas pelo pesquisador e aparecerão aqui.',
  back_button: 'Voltar',
  continue_to_dashboard: 'Continuar para o Painel',
  assessment_summary_title: 'Resumo da Avaliação',
  assessment_summary_subtitle: 'Aqui estão seus resultados. Seu plano de treino será ajustado com base neles.',
  classification: 'Classificação',
  classification_good: 'Bom',
  classification_average: 'Médio',
  classification_attention: 'Requer Atenção',
  duration_reps: '{count} repetições',
  duration_reps_sets: '{count} reps × {sets} séries',
  duration_seconds: '{count}s',
  duration_minutes: '{count} min',
  duration_seconds_per_leg: '{count}s por perna',
  duration_seconds_per_arm: '{count}s por braço',
  duration_steps: '{count} passos',
  duration_per_side: '{count} por lado',
  session_type_strength: 'Força',
  session_type_balance: 'Equilíbrio',
  session_type_flexibility: 'Flexibilidade',
  session_type_cardio: 'Cardiorrespiratório',
  session_type_posture: 'Postural',
  exercise_marching_in_place: 'Marcha estacionária',
  exercise_arm_circles: 'Círculos com os braços',
  exercise_sit_to_stand: 'Sentar e levantar',
  exercise_wall_push_ups: 'Flexões na parede',
  exercise_tandem_stance: 'Postura tândem',
  exercise_heel_raises: 'Elevação de calcanhares',
  exercise_hamstring_stretch: 'Alongamento de isquiotibiais',
  exercise_calf_stretch: 'Alongamento de panturrilha',
  exercise_step_ups: 'Subir degrau',
  exercise_bicep_curls: 'Rosca bíceps (com peso leve)',
  exercise_lateral_leg_raises: 'Elevação lateral de perna',
  exercise_single_leg_stance: 'Apoio unipodal',
  exercise_heel_to_toe_walk: 'Caminhada calcanhar-ponta do pé',
  exercise_chair_yoga_poses: 'Poses de ioga na cadeira',
  exercise_shoulder_stretch: 'Alongamento de ombros',
  exercise_chest_stretch: 'Alongamento de peitoral',
  exercise_seated_rowing: 'Remada sentada (com elástico)',
  exercise_brisk_walking: 'Caminhada rápida (no lugar)',
  exercise_knee_highs: 'Elevação de joelhos',
  exercise_cat_cow_stretch: 'Alongamento gato-vaca',
  exercise_bird_dog: 'Pássaro-cão',
  exercise_pelvic_tilt: 'Inclinação pélvica',
  safety_note_title: 'CONSELHO DE SEGURANÇA',
  instruction_sit_to_stand: 'Sente-se em uma cadeira firme. Levante-se até ficar totalmente de pé e sente-se novamente de forma controlada.',
  safety_sit_to_stand: 'Certifique-se de que a cadeira não deslize. Mantenha os joelhos alinhados com os pés.',
  instruction_wall_push_ups: 'Fique de frente para uma parede, coloque as mãos na altura dos ombros. Dobre os cotovelos para aproximar o peito da parede e empurre de volta.',
  safety_wall_push_ups: 'Mantenha o corpo reto como uma prancha. Use calçados antiderrapantes.',
  instruction_step_ups: 'Use um degrau firme. Suba com uma perna e desça de forma controlada. Alterne as pernas.',
  safety_step_ups: 'Tenha um apoio próximo caso perca o equilíbrio. O degrau deve ser estável.',
  instruction_bicep_curls: 'Segure um peso leve em cada mão. Dobre os cotovelos para levantar os pesos em direção aos ombros e abaixe lentamente.',
  safety_bicep_curls: 'Mantenha os cotovelos próximos ao corpo. Não balance o tronco.',
  instruction_lateral_leg_raises: 'Em pé, segure-se em uma cadeira. Levante uma perna para o lado sem inclinar o tronco e retorne.',
  safety_lateral_leg_raises: 'Mantenha a postura ereta. O movimento deve ser lento e controlado.',
  instruction_heel_raises: 'Em pé, apoiado em uma cadeira, levante os calcanhares ficando na ponta dos pés e desça lentamente.',
  safety_heel_raises: 'Use o apoio apenas para equilíbrio, não puxe a cadeira.',
  instruction_single_leg_stance: 'Fique em um pé só, mantendo o equilíbrio. Use uma cadeira como apoio se necessário.',
  safety_single_leg_stance: 'Mantenha-se perto de uma parede ou cadeira firme para evitar quedas.',
  instruction_tandem_stance: 'Coloque um pé exatamente na frente do outro (calcanhar tocando os dedos) e mantenha o equilíbrio.',
  safety_tandem_stance: 'Faça o exercício perto de uma parede ou apoio.',
  instruction_heel_to_toe_walk: 'Caminhe em linha reta colocando o calcanhar de um pé logo à frente dos dedos do outro pé.',
  safety_heel_to_toe_walk: 'Olhe para a frente, não para o chão. Tenha uma parede próxima.',
  instruction_arm_circles: 'Estenda os braços para os lados e faça pequenos círculos para frente e depois para trás.',
  safety_arm_circles: 'Mantenha os ombros relaxados, longe das orelhas.',
  instruction_hamstring_stretch: 'Sente-se na ponta de uma cadeira, estique uma perna com o calcanhar no chão. Incline o tronco para frente.',
  safety_hamstring_stretch: 'Mantenha as costas retas. Vá apenas até sentir um alongamento suave.',
  instruction_calf_stretch: 'Fique de frente para uma parede. Dê um passo para trás com uma perna, mantendo o calcanhar no chão e o joelho esticado.',
  safety_calf_stretch: 'Mantenha os pés apontados para frente. Não force além do limite confortável.',
  instruction_shoulder_stretch: 'Puxe um braço através do peito usando a outra mão, alongando o ombro.',
  safety_shoulder_stretch: 'Não puxe pela articulação do cotovelo, puxe pelo braço ou antebraço.',
  instruction_chest_stretch: 'Entrelace as mãos atrás das costas e levante levemente os braços para abrir o peito.',
  safety_chest_stretch: 'Mantenha o pescoço neutro. Não force os ombros.',
  instruction_brisk_walking: 'Caminhe em um ritmo acelerado, mas que permita manter uma conversa.',
  safety_brisk_walking: 'Use calçados confortáveis e caminhe em local plano e seguro.',
  instruction_marching_in_place: 'Marche no mesmo lugar, levantando os joelhos e movendo os braços.',
  safety_marching_in_place: 'Mantenha o abdômen contraído e a postura ereta.',
  instruction_knee_highs: 'Em pé, levante um joelho de cada vez o mais alto que conseguir de forma confortável.',
  safety_knee_highs: 'Use uma cadeira para apoio se sentir desequilíbrio.',
  instruction_seated_rowing: 'Sentado, segure um elástico preso à frente. Puxe as mãos em direção à cintura, apertando as escápulas.',
  safety_seated_rowing: 'Mantenha a coluna reta. Verifique se o elástico está bem preso.',
  instruction_cat_cow_stretch: 'Na posição de quatro apoios, alterne entre curvar as costas para cima (gato) e para baixo (vaca).',
  safety_cat_cow_stretch: 'Faça movimentos suaves. Evite se tiver dor nos pulsos ou joelhos.',
  instruction_bird_dog: 'Na posição de quatro apoios, estenda um braço e a perna oposta simultaneamente. Alterne os lados.',
  safety_bird_dog: 'Mantenha o pescoço alinhado com a coluna e o abdômen firme.',
  instruction_pelvic_tilt: 'Deitado de barriga para cima, joelhos dobrados. Eleve o quadril do chão até formar uma linha reta dos joelhos aos ombros.',
  safety_pelvic_tilt: 'Mantenha os pés firmes no chão e não force o pescoço.',
  series_label: 'SÉRIES',
  repetitions_label: 'REPETIÇÕES',
  duration_label: 'DURAÇÃO',
  exit_session: 'Sair da Sessão',
  belt_white: 'Faixa Branca',
  belt_yellow: 'Faixa Amarela',
  belt_orange: 'Faixa Laranja',
  belt_green: 'Faixa Verde',
  belt_blue: 'Faixa Azul',
  belt_black: 'Faixa Preta',
  current_belt: 'Sua Faixa Atual',
  motivational_pre_session: 'Vamos fortalecer seu corpo hoje para garantir mais saúde e independência!',
  motivational_post_session: 'Excelente trabalho! Cada sessão concluída é um passo a mais para a sua qualidade de vida.',
  motivational_pre_1: 'A consistência é a chave! Vamos para mais um treino excelente.',
  motivational_pre_2: 'Seu corpo é sua casa. Vamos cuidar bem dele hoje.',
  motivational_pre_3: 'Lembre-se: cada movimento conta para a sua independência.',
  motivational_post_1: 'Missão cumprida! Descanse bem, você mereceu.',
  motivational_post_2: 'Incrível! Você está construindo uma versão mais forte de si mesmo.',
  motivational_post_3: 'Mais um passo rumo aos seus objetivos. Parabéns pela dedicação!',
  report_incident: 'Relatar Incidente',
  incident_title: 'Relatório de Segurança',
  incident_desc: 'Você teve alguma queda, dor incomum ou tontura forte durante a última semana?',
  incident_yes: 'Sim, tive um incidente',
  incident_no: 'Não, tudo ocorreu bem',
  incident_reported: 'Obrigado por relatar. Um pesquisador entrará em contato em breve.',
  start_workout: 'Começar Treino',
  my_training_plan_title: 'Meu Plano de Treino',
  training_plan_not_generated: 'Plano de treino ainda não gerado. Aguarde a avaliação com o pesquisador.',
  training_plan_desc: 'Este é o seu plano de 8 semanas, personalizado com base na sua avaliação.',
  day: 'Dia',
  level: 'Nível',
  completed: 'CONCLUÍDO',
  next_session: 'PRÓXIMA SESSÃO',
  exercise_x_of_y: 'Exercício {current} de {total}',
  previous: 'Anterior',
  next: 'Próximo',
  program_not_found: 'Programa de treino não encontrado ou participante inválido.',
  view_full_plan: 'Ver Plano Completo',
  select_metric: 'Selecionar Métrica',
  percent_change: 'Mudança %',
  week: 'Semana',
  export_csv: 'Exportar para CSV',
  researcher_table_id: 'ID',
  researcher_table_site: 'Polo',
  researcher_table_sessions: 'Sessões',
  researcher_table_adherence: 'Adesão',
  researcher_table_last_assessment: 'Últ. Avaliação',
  researcher_table_grip: 'Força',
  researcher_table_balance: 'Equilíbrio',
  researcher_table_flexibility: 'Flexibilidade',
  researcher_table_bmi: 'IMC',
  participant_name: 'Nome',
  participant_sex: 'Sexo',
  participant_age: 'Idade',
  years_old: 'anos',
  participant_dob: 'Data de Nascimento',
  sex_m: 'Masculino',
  sex_f: 'Feminino',
  sex_other: 'Outro',
  happy_birthday: 'Feliz Aniversário! 🎉',
  happy_birthday_msg: 'Parabéns pelo seu dia! Que este novo ano de vida traga ainda mais saúde e disposição.',
  researcher_table_name: 'Nome',
  researcher_table_sex: 'Sexo',
  researcher_table_age: 'Idade',
  confirm_end_session: 'Deseja encerrar a sessão atual e voltar ao início?',
  confirm_reset_all: 'ATENÇÃO: Deseja também ZERAR TODOS OS DADOS (apagar todos os participantes e avaliações) para reiniciar o programa do zero?',
  login_subtitle: 'Acesse o programa com seu código e senha.',
  login_access_code: 'Código de acesso',
  login_access_code_placeholder: 'Ex: BR-001',
  login_password: 'Senha',
  login_password_placeholder: 'DD/MM/AAAA',
  login_password_hint: 'Participantes: informe sua data de nascimento no formato DD/MM/AAAA.',
  login_submit: 'Entrar',
  login_error: 'Código ou senha inválidos. Verifique os dados e tente novamente.',
  login_new_participant: 'Ainda não tem cadastro?',
  login_enroll_link: 'Iniciar cadastro como novo participante',
  awaiting_first_assessment: 'Seu pesquisador realizará a avaliação física e seu plano de treino personalizado será gerado a seguir.',
  next_session_personalized_hint: 'Seu plano de treino personalizado selecionou esta sessão para focar nas suas metas.',
  my_training_plan_desc: 'Veja a sequência completa de 24 sessões elaborada para você.',
  back_to_dashboard: 'Voltar ao Painel',
  readonly_badge: 'Somente Leitura',
  new_participant: 'Novo Participante',
  view_participant_panel: 'Ver Painel',
  assessment_history_title: 'Histórico de Avaliações',
  alerts_title: 'Alertas',
  alerts_subtitle: 'Incidentes reportados pelos participantes durante as sessões.',
  alerts_no_incidents: 'Nenhum incidente reportado até o momento.',
  mark_reviewed: 'Marcar Resolvido',
  alert_reviewed: 'Resolvido',
  alert_pending: 'Pendente',
  unreviewed_badge: '{count} pendente(s)',
  alerts_col_participant: 'Participante',
  alerts_col_session: 'Sessão',
  alerts_col_date: 'Data',
  alerts_col_status: 'Status',
  alerts_col_action: 'Ação',
  session_number_label: 'Sessão {number}',
  register_participant_title: 'Cadastro de Novo Participante',
  register_participant_intro: 'Preencha os dados do participante. A data de nascimento será usada como senha de acesso.',
  study_id_label: 'ID do Participante no Estudo',
  study_id_hint: 'Se deixado em branco, um ID será gerado automaticamente.',
  site_label: 'Polo',
  birth_date_password_hint: 'Esta data será usada como senha de acesso do participante.',
  enrollment_save_and_return: 'Salvar e Voltar ao Painel',
  register_assessment: 'Registrar Avaliação',
  // Bilingualism corrections — hardcoded strings moved to i18n
  participant_not_found: 'Participante não encontrado.',
  participant_session_expired: 'Participante não encontrado ou sessão expirada.',
  back_to_start: 'Voltar ao Início',
  table_col_actions: 'Ações',
  ready_to_start: 'Pronto para começar?',
  no_assessment_data: 'Nenhum dado de avaliação encontrado.',
  click_session_hint: 'Clique em uma sessão para ver os exercícios.',
  level_abbr: 'Nv',
  full_name_placeholder: 'Nome completo',
  // Alerts page
  alerts_col_occurrence: 'Ocorrência',
  alerts_col_action_taken: 'Providência',
  incident_occurrence_placeholder: 'Descreva o que aconteceu...',
  incident_action_placeholder: 'Descreva a providência adotada...',
  // Metric group labels (dropdown)
  metric_group_body_comp: 'Composição Corporal',
  metric_group_strength: 'Força e Função',
  metric_group_mobility: 'Mobilidade',
  metric_group_aerobic: 'Capacidade Aeróbica',
  close_modal: 'Fechar',
  session_modal_level: 'Nível {level}',
  // Assessment stations
  assessment_station1: 'Estação 1 — Composição Corporal',
  assessment_station2: 'Estação 2 — Força e Agilidade',
  assessment_station3: 'Estação 3 — Capacidade Aeróbica',
  waist_circumference: 'Circunferência da Cintura (cm)',
  hip_circumference: 'Circunferência do Quadril (cm)',
  body_fat_percent: 'Percentual de Gordura (%)',
  waist_hip_ratio: 'Relação Cintura-Quadril (RCQ)',
  handgrip_dominant: 'Preensão — Mão Dominante (kgf)',
  handgrip_nondominant: 'Preensão — Mão Não-Dominante (kgf)',
  chair_stand_test: 'Sentar e Levantar (rep)',
  arm_curl_test: 'Rosca Bíceps (rep)',
  chair_sit_reach: 'Sentar e Alcançar (cm)',
  up_and_go: 'Levantar e Caminhar (s)',
  six_min_walk: 'TC6 — Caminhada 6 Minutos (m)',
  six_min_walk_predicted: 'Distância Prevista (m)',
  six_min_walk_percent: 'Percentual do Previsto (%)',
};