import { I18nKeys } from './es';

export const pt: I18nKeys = {
  welcome_title: 'Programa Envelhecimento Ativo',
  welcome_subtitle: 'Bem-vindo ao aplicativo de apoio ao estudo. Selecione seu idioma para começar.',
  select_language: 'Selecionar Idioma',
  portuguese: 'Português (Brasil)',
  spanish: 'Espanhol (Espanha)',
  continue: 'Continuar',
  consent_title: 'Termo de Consentimento Livre e Esclarecido',
  consent_intro: 'Por favor, leia o documento a seguir com atenção. Sua participação é voluntária.',
  consent_item1_title: '1. Objetivo do Estudo',
  consent_item1_desc: 'O objetivo deste estudo é avaliar os efeitos de um programa de exercícios físicos na saúde e qualidade de vida de idosos.',
  consent_item2_title: '2. Procedimentos',
  consent_item2_desc: 'Você participará de sessões de exercícios físicos regulares e realizará avaliações físicas periódicas (força, equilíbrio, flexibilidade, etc.).',
  consent_item3_title: '3. Riscos e Benefícios',
  consent_item3_desc: 'Os riscos são mínimos e semelhantes aos da prática regular de exercícios físicos, como fadiga muscular leve. Os benefícios esperados incluem melhora na capacidade funcional, força e bem-estar geral.',
  consent_item4_title: '4. Confidencialidade e Voluntariedade',
  consent_item4_desc: 'Seus dados serão mantidos em sigilo absoluto e usados apenas para fins de pesquisa. Sua participação é totalmente voluntária, podendo você desistir a qualquer momento sem penalidades.',
  consent_accept: 'Li e aceito participar',
  consent_decline: 'Não aceito participar',
  screening_title: 'Triagem Clínica',
  screening_intro: 'Responda às seguintes perguntas para garantir sua segurança durante o estudo.',
  screening_q1: 'Algum médico já lhe disse que você tem um problema de coração e que só deveria realizar atividade física supervisionado por profissionais de saúde?',
  screening_q2: 'Você sente dor no peito ao fazer atividade física?',
  screening_q3: 'No último mês, você sentiu dor no peito quando não estava fazendo atividade física?',
  screening_q4: 'Você perde o equilíbrio por tontura ou alguma vez perdeu a consciência?',
  screening_q5: 'Você tem algum problema ósseo ou articular (por exemplo, nas costas, joelho ou quadril) que poderia ser agravado pela atividade física?',
  screening_submit: 'Enviar Respostas',
  contact_professional: 'Com base em suas respostas, por favor, contate um profissional antes de continuar.',
  screening_success_title: 'Triagem Concluída',
  screening_success_message: 'Você está pronto para começar! Pressione continuar para ir ao seu painel.',
  dashboard_participant_title: 'Meu Painel',
  dashboard_researcher_title: 'Painel do Pesquisador',
  next_session_title: 'Próxima Sessão de Treino',
  next_session_info: 'Sessão {sessionNumber}: {sessionType}',
  next_session_info_with_level: 'Sessão {sessionNumber}: {sessionType} - Nível {level}',
  start_session: 'Iniciar Sessão',
  training_complete: 'Parabéns! Você completou seu programa de treino.',
  sessions_completed: 'Sessões Concluídas',
  adherence_rate: 'Taxa de Adesão',
  new_assessment: 'Nova Avaliação',
  assessment_title: 'Registro de Avaliação',
  handgrip_strength: 'Força de Preensão Manual (kgf)',
  balance: 'Equilíbrio (s, apoio unipodal)',
  flexibility: 'Flexibilidade (cm, Teste de Tocar as Mãos nas Costas)',
  weight: 'Peso (kg)',
  height: 'Altura (cm)',
  calf_circumference: 'Circunferência da Panturrilha (cm)',
  bmi: 'Índice de Massa Corporal (IMC)',
  cc_bmi_index: 'Índice Alométrico (CP·IMC⁻¹)',
  save_assessment: 'Salvar Avaliação',
  assessment_saved_success: 'Avaliação salva com sucesso!',
  session_title: 'Sessão de Treino: {sessionType}',
  complete_session: 'Concluir Sessão',
  difficulty_feedback: 'Como foi a sessão?',
  easy: 'Fácil',
  adequate: 'Adequada',
  hard: 'Difícil',
  participant_view: 'Visão do Participante',
  researcher_view: 'Visão do Pesquisador',
  participants: 'Participantes',
  site_brazil: 'Polo Brasil',
  site_spain: 'Polo Espanha',
  adherence_chart_title: 'Taxa de Adesão por Semana',
  pre_post_chart_title: 'Comparativo Pré vs. Pós (Média)',
  select_participant: 'Selecionar Participante',
  yes: 'Sim',
  no: 'Não',
  my_assessments_title: 'Minhas Avaliações',
  my_assessments_desc: 'Realize uma nova avaliação para acompanhar seu progresso.',
  my_progress_title: 'Meu Progresso',
  no_assessments_yet: 'As avaliações serão registradas pelo pesquisador e aparecerão aqui.',
  back_button: 'Voltar',
  continue_to_dashboard: 'Continuar para o Painel',
  assessment_summary_title: 'Resumo da Avaliação',
  assessment_summary_subtitle: 'Aqui estão seus resultados. Seu plano de treino será ajustado com base neles.',
  classification: 'Classificação',
  classification_good: 'Bom',
  classification_average: 'Médio',
  classification_attention: 'Requer Atenção',
  duration_reps: '{count} repetições',
  duration_reps_sets: '{count} reps × {sets} séries',
  duration_seconds: '{count}s',
  duration_minutes: '{count} min',
  duration_seconds_per_leg: '{count}s por perna',
  duration_seconds_per_arm: '{count}s por braço',
  duration_steps: '{count} passos',
  duration_per_side: '{count} por lado',
  session_type_session1: 'Sessão A — Multicomponente',
  session_type_session2: 'Sessão B — Multicomponente',
  session_type_session3: 'Sessão C — Multicomponente',
  exercise_marching_in_place: 'Marcha estacionária',
  exercise_arm_circles: 'Círculos com os braços',
  exercise_sit_to_stand: 'Sentar e levantar',
  exercise_wall_push_ups: 'Flexões na parede',
  exercise_tandem_stance: 'Postura tândem',
  exercise_heel_raises: 'Elevação de calcanhares',
  exercise_hamstring_stretch: 'Alongamento de isquiotibiais',
  exercise_calf_stretch: 'Alongamento de panturrilha',
  exercise_step_ups: 'Subir degrau',
  exercise_bicep_curls: 'Rosca bíceps (com peso leve)',
  exercise_lateral_leg_raises: 'Elevação lateral de perna',
  exercise_single_leg_stance: 'Apoio unipodal',
  exercise_heel_to_toe_walk: 'Caminhada calcanhar-ponta do pé',
  exercise_chair_yoga_poses: 'Poses de ioga na cadeira',
  exercise_shoulder_stretch: 'Alongamento de ombros',
  exercise_chest_stretch: 'Alongamento de peitoral',
  exercise_seated_rowing: 'Remada sentada (com elástico)',
  exercise_brisk_walking: 'Caminhada rápida (no lugar)',
  exercise_knee_highs: 'Elevação de joelhos',
  exercise_cat_cow_stretch: 'Alongamento gato-vaca',
  exercise_bird_dog: 'Pássaro-cão',
  exercise_pelvic_tilt: 'Inclinação pélvica',
  safety_note_title: 'CONSELHO DE SEGURANÇA',
  instruction_sit_to_stand: 'Sente-se em uma cadeira firme. Levante-se até ficar totalmente de pé e sente-se novamente de forma controlada.',
  safety_sit_to_stand: 'Certifique-se de que a cadeira não deslize. Mantenha os joelhos alinhados com os pés.',
  instruction_wall_push_ups: 'Fique de frente para uma parede, coloque as mãos na altura dos ombros. Dobre os cotovelos para aproximar o peito da parede e empurre de volta.',
  safety_wall_push_ups: 'Mantenha o corpo reto como uma prancha. Use calçados antiderrapantes.',
  instruction_step_ups: 'Use um degrau firme. Suba com uma perna e desça de forma controlada. Alterne as pernas.',
  safety_step_ups: 'Tenha um apoio próximo caso perca o equilíbrio. O degrau deve ser estável.',
  instruction_bicep_curls: 'Segure um peso leve em cada mão. Dobre os cotovelos para levantar os pesos em direção aos ombros e abaixe lentamente.',
  safety_bicep_curls: 'Mantenha os cotovelos próximos ao corpo. Não balance o tronco.',
  instruction_lateral_leg_raises: 'Em pé, segure-se em uma cadeira. Levante uma perna para o lado sem inclinar o tronco e retorne.',
  safety_lateral_leg_raises: 'Mantenha a postura ereta. O movimento deve ser lento e controlado.',
  instruction_heel_raises: 'Em pé, apoiado em uma cadeira, levante os calcanhares ficando na ponta dos pés e desça lentamente.',
  safety_heel_raises: 'Use o apoio apenas para equilíbrio, não puxe a cadeira.',
  instruction_single_leg_stance: 'Fique em um pé só, mantendo o equilíbrio. Use uma cadeira como apoio se necessário.',
  safety_single_leg_stance: 'Mantenha-se perto de uma parede ou cadeira firme para evitar quedas.',
  instruction_tandem_stance: 'Coloque um pé exatamente na frente do outro (calcanhar tocando os dedos) e mantenha o equilíbrio.',
  safety_tandem_stance: 'Faça o exercício perto de uma parede ou apoio.',
  instruction_heel_to_toe_walk: 'Caminhe em linha reta colocando o calcanhar de um pé logo à frente dos dedos do outro pé.',
  safety_heel_to_toe_walk: 'Olhe para a frente, não para o chão. Tenha uma parede próxima.',
  instruction_arm_circles: 'Estenda os braços para os lados e faça pequenos círculos para frente e depois para trás.',
  safety_arm_circles: 'Mantenha os ombros relaxados, longe das orelhas.',
  instruction_hamstring_stretch: 'Sente-se na ponta de uma cadeira, estique uma perna com o calcanhar no chão. Incline o tronco para frente.',
  safety_hamstring_stretch: 'Mantenha as costas retas. Vá apenas até sentir um alongamento suave.',
  instruction_calf_stretch: 'Fique de frente para uma parede. Dê um passo para trás com uma perna, mantendo o calcanhar no chão e o joelho esticado.',
  safety_calf_stretch: 'Mantenha os pés apontados para frente. Não force além do limite confortável.',
  instruction_shoulder_stretch: 'Puxe um braço através do peito usando a outra mão, alongando o ombro.',
  safety_shoulder_stretch: 'Não puxe pela articulação do cotovelo, puxe pelo braço ou antebraço.',
  instruction_chest_stretch: 'Entrelace as mãos atrás das costas e levante levemente os braços para abrir o peito.',
  safety_chest_stretch: 'Mantenha o pescoço neutro. Não force os ombros.',
  instruction_brisk_walking: 'Caminhe em um ritmo acelerado, mas que permita manter uma conversa.',
  safety_brisk_walking: 'Use calçados confortáveis e caminhe em local plano e seguro.',
  instruction_marching_in_place: 'Marche no mesmo lugar, levantando os joelhos e movendo os braços.',
  safety_marching_in_place: 'Mantenha o abdômen contraído e a postura ereta.',
  instruction_knee_highs: 'Em pé, levante um joelho de cada vez o mais alto que conseguir de forma confortável.',
  safety_knee_highs: 'Use uma cadeira para apoio se sentir desequilíbrio.',
  instruction_seated_rowing: 'Sentado, segure um elástico preso à frente. Puxe as mãos em direção à cintura, apertando as escápulas.',
  safety_seated_rowing: 'Mantenha a coluna reta. Verifique se o elástico está bem preso.',
  instruction_cat_cow_stretch: 'Na posição de quatro apoios, alterne entre curvar as costas para cima (gato) e para baixo (vaca).',
  safety_cat_cow_stretch: 'Faça movimentos suaves. Evite se tiver dor nos pulsos ou joelhos.',
  instruction_bird_dog: 'Na posição de quatro apoios, estenda um braço e a perna oposta simultaneamente. Alterne os lados.',
  safety_bird_dog: 'Mantenha o pescoço alinhado com a coluna e o abdômen firme.',
  instruction_pelvic_tilt: 'Deitado de barriga para cima, joelhos dobrados. Eleve o quadril do chão até formar uma linha reta dos joelhos aos ombros.',
  safety_pelvic_tilt: 'Mantenha os pés firmes no chão e não force o pescoço.',
  warmup_phase_label: 'AQUECIMENTO',
  warmup_phase_desc: 'Prepare seu corpo com estes exercícios antes da atividade principal.',
  start_main_activity: 'Iniciar Atividade Principal',
  cooldown_phase_label: 'DESAQUECIMENTO',
  cooldown_phase_desc: 'Alongue os músculos trabalhados para se recuperar corretamente.',
  finish_cooldown: 'Finalizar Sessão',
  series_label: 'SÉRIES',
  repetitions_label: 'REPETIÇÕES',
  duration_label: 'DURAÇÃO',
  exit_session: 'Sair da Sessão',
  belt_white: 'Faixa Branca',
  belt_yellow: 'Faixa Amarela',
  belt_orange: 'Faixa Laranja',
  belt_green: 'Faixa Verde',
  belt_blue: 'Faixa Azul',
  belt_black: 'Faixa Preta',
  current_belt: 'Sua Faixa Atual',
  motivational_pre_session: 'Vamos fortalecer seu corpo hoje para garantir mais saúde e independência!',
  motivational_post_session: 'Excelente trabalho! Cada sessão concluída é um passo a mais para a sua qualidade de vida.',
  motivational_pre_1: 'A consistência é a chave! Vamos para mais um treino excelente.',
  motivational_pre_2: 'Seu corpo é sua casa. Vamos cuidar bem dele hoje.',
  motivational_pre_3: 'Lembre-se: cada movimento conta para a sua independência.',
  motivational_post_1: 'Missão cumprida! Descanse bem, você mereceu.',
  motivational_post_2: 'Incrível! Você está construindo uma versão mais forte de si mesmo.',
  motivational_post_3: 'Mais um passo rumo aos seus objetivos. Parabéns pela dedicação!',
  report_incident: 'Relatar Incidente',
  incident_title: 'Relatório de Segurança',
  incident_desc: 'Você teve alguma queda, dor incomum ou tontura forte durante a última semana?',
  incident_yes: 'Sim, tive um incidente',
  incident_no: 'Não, tudo ocorreu bem',
  incident_reported: 'Obrigado por relatar. Um pesquisador entrará em contato em breve.',
  start_workout: 'Começar Treino',
  my_training_plan_title: 'Meu Plano de Treino',
  training_plan_not_generated: 'Plano de treino ainda não gerado. Aguarde a avaliação com o pesquisador.',
  training_plan_desc: 'Este é o seu plano de 8 semanas, personalizado com base na sua avaliação.',
  day: 'Dia',
  level: 'Nível',
  completed: 'CONCLUÍDO',
  next_session: 'PRÓXIMA SESSÃO',
  exercise_x_of_y: 'Exercício {current} de {total}',
  previous: 'Anterior',
  next: 'Próximo',
  program_not_found: 'Programa de treino não encontrado ou participante inválido.',
  view_full_plan: 'Ver Plano Completo',
  select_metric: 'Selecionar Métrica',
  percent_change: 'Mudança %',
  week: 'Semana',
  export_csv: 'Exportar para CSV',
  researcher_table_id: 'ID',
  researcher_table_site: 'Polo',
  researcher_table_sessions: 'Sessões',
  researcher_table_adherence: 'Adesão',
  researcher_table_last_assessment: 'Últ. Avaliação',
  researcher_table_grip: 'Força',
  researcher_table_balance: 'Equilíbrio',
  researcher_table_flexibility: 'Flexibilidade',
  researcher_table_bmi: 'IMC',
  participant_name: 'Nome',
  participant_sex: 'Sexo',
  participant_age: 'Idade',
  years_old: 'anos',
  participant_dob: 'Data de Nascimento',
  sex_m: 'Masculino',
  sex_f: 'Feminino',
  sex_other: 'Outro',
  happy_birthday: 'Feliz Aniversário! 🎉',
  happy_birthday_msg: 'Parabéns pelo seu dia! Que este novo ano de vida traga ainda mais saúde e disposição.',
  researcher_table_name: 'Nome',
  researcher_table_sex: 'Sexo',
  researcher_table_age: 'Idade',
  confirm_end_session: 'Deseja encerrar a sessão atual e voltar ao início?',
  confirm_reset_all: 'Esta ação apagará permanentemente todos os participantes e avaliações. Não pode ser desfeita.',
  login_subtitle: 'Acesse o programa com seu código e senha.',
  login_access_code: 'Código de acesso',
  login_access_code_placeholder: 'Ex: BR-001',
  login_password: 'Senha',
  login_password_placeholder: '19570618',
  login_password_hint: 'Informe sua data de nascimento no formato AAAAMMDD (ex: 19570618)',
  login_submit: 'Entrar',
  login_error: 'Código ou senha inválidos. Verifique os dados e tente novamente.',
  login_new_participant: 'Ainda não tem cadastro?',
  login_enroll_link: 'Iniciar cadastro como novo participante',
  awaiting_first_assessment: 'Seu pesquisador realizará a avaliação física e seu plano de treino personalizado será gerado a seguir.',
  next_session_personalized_hint: 'Seu plano de treino personalizado selecionou esta sessão para focar nas suas metas.',
  my_training_plan_desc: 'Veja a sequência completa de 24 sessões elaborada para você.',
  back_to_dashboard: 'Voltar ao Painel',
  readonly_badge: 'Somente Leitura',
  new_participant: 'Novo Participante',
  view_participant_panel: 'Ver Painel',
  assessment_history_title: 'Histórico de Avaliações',
  alerts_title: 'Alertas',
  alerts_subtitle: 'Incidentes reportados pelos participantes durante as sessões.',
  alerts_no_incidents: 'Nenhum incidente reportado até o momento.',
  mark_reviewed: 'Marcar Resolvido',
  alert_reviewed: 'Resolvido',
  alert_pending: 'Pendente',
  unreviewed_badge: '{count} pendente(s)',
  alerts_col_participant: 'Participante',
  alerts_col_session: 'Sessão',
  alerts_col_date: 'Data',
  alerts_col_status: 'Status',
  alerts_col_action: 'Ação',
  session_number_label: 'Sessão {number}',
  register_participant_title: 'Cadastro de Novo Participante',
  register_participant_intro: 'Preencha os dados do participante. A data de nascimento será usada como senha de acesso.',
  study_id_label: 'ID do Participante no Estudo',
  study_id_hint: 'Se deixado em branco, um ID será gerado automaticamente.',
  site_label: 'Polo',
  birth_date_password_hint: 'Esta data será usada como senha de acesso do participante.',
  enrollment_save_and_return: 'Salvar e Voltar ao Painel',
  register_assessment: 'Registrar Avaliação',
  logout_button: 'Sair',
  // Bilingualism corrections — hardcoded strings moved to i18n
  participant_not_found: 'Participante não encontrado.',
  participant_session_expired: 'Participante não encontrado ou sessão expirada.',
  back_to_start: 'Voltar ao Início',
  table_col_actions: 'Ações',
  ready_to_start: 'Pronto para começar?',
  no_assessment_data: 'Nenhum dado de avaliação encontrado.',
  click_session_hint: 'Clique em uma sessão para ver os exercícios.',
  level_abbr: 'Nv',
  full_name_placeholder: 'Nome completo',
  // Alerts page
  alerts_col_occurrence: 'Ocorrência',
  alerts_col_action_taken: 'Providência',
  incident_occurrence_placeholder: 'Descreva o que aconteceu...',
  incident_action_placeholder: 'Descreva a providência adotada...',
  // Metric group labels (dropdown)
  metric_group_body_comp: 'Composição Corporal',
  metric_group_strength: 'Força e Função',
  metric_group_mobility: 'Mobilidade',
  metric_group_aerobic: 'Capacidade Aeróbica',
  close_modal: 'Fechar',
  session_modal_level: 'Nível {level}',
  // Assessment stations
  assessment_station1: 'Estação 1 — Composição Corporal',
  assessment_station2: 'Estação 2 — Força e Agilidade',
  assessment_station3: 'Estação 3 — Capacidade Aeróbica',
  waist_circumference: 'Circunferência da Cintura (cm)',
  hip_circumference: 'Circunferência do Quadril (cm)',
  body_fat_percent: 'Percentual de Gordura (%)',
  waist_hip_ratio: 'Relação Cintura-Quadril (RCQ)',
  handgrip_dominant: 'Preensão — Mão Dominante (kgf)',
  handgrip_nondominant: 'Preensão — Mão Não-Dominante (kgf)',
  chair_stand_test: 'Sentar e Levantar (rep)',
  arm_curl_test: 'Rosca Bíceps (rep)',
  chair_sit_reach: 'Sentar e Alcançar (cm)',
  up_and_go: 'Levantar e Caminhar (s)',
  six_min_walk: 'TC6 — Caminhada 6 Minutos (m)',
  six_min_walk_predicted: 'Distância Prevista (m)',
  six_min_walk_percent: 'TC6 — Percentual do Previsto (%)',
  // Country labels (site field)
  country_brazil: 'Brasil',
  country_spain: 'Espanha',
  // Table headers — TC6
  researcher_table_tc6: 'TC6 (m)',
  researcher_table_tc6_percent: 'TC6 — % Previsto',
  // Header modals
  home_tooltip: 'Início / Reiniciar',
  end_session_title: 'Encerrar Sessão',
  cancel: 'Cancelar',
  confirm_end_session_yes: 'Sim, encerrar',
  reset_data_title: 'Atenção: Zerar Dados',
  reset_data_no: 'Não, apenas sair',
  reset_data_yes: 'Apagar Todos os Dados',
  login_loading: 'Carregando dados...',
  login_connection_error: 'Não foi possível conectar ao servidor. Verifique sua conexão e tente novamente.',
  // Screening
  study_id_placeholder: 'Ex: BR-004',
  // Session history table (researcher view)
  session_history_title: 'Histórico de Sessões',
  session_history_col_session: 'Sessão',
  session_history_col_date: 'Data',
  session_history_col_start: 'Início',
  session_history_col_end: 'Fim',
  session_history_col_duration: 'Duração (min)',
  session_history_col_completed: 'Concluída',
  session_history_completed_yes: 'Sim',
  session_history_completed_no: 'Não',
  // RPE por exercício (Asier Fase 1)
  rpe_zone_label: 'Esforço esperado',
  load_rec_label: 'Carga sugerida',
  rpe_talk_test: 'Você deve conseguir falar frases curtas durante o exercício',
  rpe_picker_title: 'Como foi o esforço nesse exercício?',
  rpe_light: '🟢 Leve',
  rpe_moderate: '🟡 Moderado',
  rpe_hard: '🔴 Intenso',
  rpe_light_desc: 'RPE ≤ 4 — Muito fácil',
  rpe_moderate_desc: 'RPE 5–6 — Na zona ideal',
  rpe_hard_desc: 'RPE ≥ 7 — Muito difícil',
  // ── Novos exercícios de aquecimento (AQ-01 a AQ-09) ──────────────────────
  exercise_ankle_circles: 'Círculos com os tornozelos',
  exercise_knee_flexion_extension: 'Flexão-extensão de joelho (sentado)',
  exercise_hip_circles: 'Círculos com o quadril',
  exercise_shoulder_circles: 'Círculos com os ombros',
  exercise_wrist_circles: 'Círculos com os pulsos',
  exercise_neck_mobility: 'Mobilidade do pescoço',
  exercise_diagonal_foot_taps: 'Toques diagonais com os pés',
  exercise_lateral_steps: 'Passos laterais',
  exercise_v_step: 'Passo em V',
  instruction_ankle_circles: 'Sentado ou de pé com apoio, levante levemente um pé do chão e faça círculos com o tornozelo, primeiro para um lado e depois para o outro. Alterne os pés.',
  instruction_knee_flexion_extension: 'Sentado em uma cadeira, estique lentamente uma perna até ficar quase reta e dobre novamente. Alterne as pernas.',
  instruction_hip_circles: 'Em pé, pés afastados na largura dos ombros e mãos no quadril, faça círculos amplos com o quadril no sentido horário e depois anti-horário.',
  instruction_shoulder_circles: 'Sentado ou em pé, eleve os ombros em direção às orelhas, gire-os para trás, para baixo e para frente. Depois inverta o sentido.',
  instruction_wrist_circles: 'Estenda os braços à frente com as mãos abertas. Faça círculos lentos com os pulsos para um lado e depois para o outro.',
  instruction_neck_mobility: 'Sentado com a coluna ereta, incline lentamente a cabeça para um lado (orelha em direção ao ombro), retorne ao centro e repita para o outro lado. Em seguida, gire suavemente a cabeça de um lado para o outro.',
  instruction_diagonal_foot_taps: 'Em pé, apoiado em uma cadeira, toque o pé direito na diagonal frontal direita, depois na lateral e depois na diagonal posterior. Repita com o pé esquerdo.',
  instruction_lateral_steps: 'Em pé, dê dois passos para a direita e depois dois para a esquerda, mantendo os joelhos levemente dobrados e o tronco ereto.',
  instruction_v_step: 'Comece com os pés juntos. Abra os pés para os lados (formando um V) e depois junte-os novamente ao centro. Mantenha um ritmo constante.',
  safety_ankle_circles: 'Faça movimentos suaves. Se estiver de pé, use apoio para não perder o equilíbrio.',
  safety_knee_flexion_extension: 'Movimento lento e controlado. Não force além do conforto, especialmente se houver dor no joelho.',
  safety_hip_circles: 'Apoie-se em uma cadeira se sentir desequilíbrio. Não force além do ângulo confortável.',
  safety_shoulder_circles: 'Movimentos lentos e suaves. Interrompa se sentir dor ou estalido no ombro.',
  safety_wrist_circles: 'Movimentos suaves. Interrompa se sentir dor ou dormência nos pulsos.',
  safety_neck_mobility: 'Nunca incline a cabeça totalmente para trás. Todos os movimentos devem ser muito lentos e controlados.',
  safety_diagonal_foot_taps: 'Segure-se na cadeira com firmeza. Não avance o toque além do equilíbrio confortável.',
  safety_lateral_steps: 'Use calçados antiderrapantes. Verifique o espaço ao redor antes de iniciar.',
  safety_v_step: 'Comece no ritmo mais lento. Use apoio se necessário.',
  // ── Novos exercícios de desaquecimento (DQ-01 a DQ-04) ───────────────────
  exercise_glute_stretch: 'Alongamento de glúteos',
  exercise_quad_stretch: 'Alongamento de quadríceps',
  exercise_back_stretch: 'Alongamento de costas',
  exercise_neck_adductor_stretch: 'Alongamento de pescoço e adutores',
  instruction_glute_stretch: 'Deitado de barriga para cima, cruze o tornozelo direito sobre o joelho esquerdo dobrado. Puxe a coxa esquerda gentilmente em direção ao peito. Mantenha e troque de lado.',
  instruction_quad_stretch: 'Em pé, apoiado em uma cadeira, dobre o joelho direito levando o calcanhar em direção ao glúteo e segure o pé com a mão direita. Mantenha e troque de lado.',
  instruction_back_stretch: 'Sentado, arredonde levemente as costas inclinando o tronco para frente, abraçando os próprios joelhos ou alongando os braços à frente. Mantenha a posição.',
  instruction_neck_adductor_stretch: 'Sentado na borda da cadeira com as pernas abertas, incline o tronco para frente alongando os adutores. Para o pescoço: incline a cabeça para um lado com leve auxílio da mão oposta.',
  safety_glute_stretch: 'Mantenha as costas apoiadas no chão. Não force o quadril além do que é confortável.',
  safety_quad_stretch: 'Mantenha-se ereto e firme no apoio. Não puxe o joelho além do ângulo confortável.',
  safety_back_stretch: 'Movimentos suaves. Evite se tiver hérnia de disco ou dor intensa nas costas.',
  safety_neck_adductor_stretch: 'Movimentos muito suaves. Não force o pescoço. Interrompa se sentir dor.',
  // Final reset confirmation modal
  reset_final_title: 'Confirmação Final — Ação Irreversível',
  reset_final_warning: 'ATENÇÃO: Esta ação apagará TODOS os participantes e avaliações do Supabase e não pode ser desfeita.',
  reset_final_type_hint: 'Digite CONFIRMAR para habilitar o botão de exclusão:',
  reset_final_button: 'Apagar Tudo e Reiniciar',

  // ── PP exercícios existentes sem i18n ────────────────────────────────────
  exercise_skipping: 'Simulação de pular corda',
  instruction_skipping: 'Em pé, simule pular uma corda imaginária: salte levemente sobre os pés alternando ou em conjunto, movendo os braços em círculo ao lado do corpo. Mantenha um ritmo constante.',
  safety_skipping: 'Use calçado com amortecimento. Reduza a altura do salto ou faça apenas o movimento dos braços se sentir desconforto nas articulações.',

  exercise_sumo_deadlift_band: 'Levantamento terra sumo com faixa',
  instruction_sumo_deadlift_band: 'Em pé com os pés mais afastados que os ombros e as pontas dos pés voltadas para fora. Pise na faixa elástica e segure as extremidades. Dobre os joelhos e o quadril para descer, depois estenda para voltar a ficar de pé apertando os glúteos no topo.',
  safety_sumo_deadlift_band: 'Mantenha as costas retas e o peito erguido durante todo o movimento. Não curve a região lombar.',

  exercise_dead_bug: 'Dead Bug (Inseto morto)',
  instruction_dead_bug: 'Deitado de costas com os braços estendidos para o teto e os joelhos dobrados a 90°. Desça lentamente um braço para trás e a perna oposta em direção ao chão sem tocá-lo. Volte ao centro. Alterne os lados.',
  safety_dead_bug: 'Mantenha a região lombar apoiada no chão durante todo o movimento. Respire de forma controlada.',

  // ── PP novos exercícios (Sessões A/B/C) ──────────────────────────────────
  exercise_lunge: 'Afundo (Lunge)',
  instruction_lunge: 'Em pé, dê um passo longo à frente com o pé direito. Desça o joelho traseiro em direção ao chão até que ambos os joelhos formem ~90°. Volte à posição inicial. Alterne as pernas.',
  safety_lunge: 'Use uma cadeira como apoio lateral se precisar de equilíbrio. O joelho da frente não deve ultrapassar a ponta do pé.',

  exercise_hip_abduction_band: 'Abdução de quadril com faixa',
  instruction_hip_abduction_band: 'Em pé, apoiado em uma cadeira, com a faixa elástica ao redor dos tornozelos. Eleve uma perna lateralmente, afastando-a do corpo, mantendo o tronco ereto. Retorne devagar. Alterne as pernas.',
  safety_hip_abduction_band: 'Mantenha-se firme no apoio. Não eleve a perna além do que o equilíbrio permitir.',

  exercise_glute_bridge_band: 'Ponte de glúteos com faixa',
  instruction_glute_bridge_band: 'Deitado de costas com joelhos dobrados e a faixa elástica acima dos joelhos. Empurre os joelhos levemente para fora e eleve o quadril do chão formando uma linha reta dos ombros aos joelhos. Desça lentamente.',
  safety_glute_bridge_band: 'Mantenha os pés bem apoiados no chão. Não curve excessivamente a região lombar.',

  exercise_rowing_with_resistance_band: 'Remada com faixa elástica',
  instruction_rowing_with_resistance_band: 'Em pé ou sentado, segure as extremidades da faixa elástica fixada à frente na altura do peito. Puxe os cotovelos para trás apertando as escápulas. Retorne lentamente à posição inicial.',
  safety_rowing_with_resistance_band: 'Mantenha as costas retas durante todo o movimento. Verifique se a faixa está bem fixada antes de começar.',

  exercise_scapular_retraction_band: 'Retração escapular com faixa',
  instruction_scapular_retraction_band: 'Em pé, segure a faixa elástica pelas duas extremidades com os braços estendidos à frente. Puxe os braços para os lados apertando as escápulas. Mantenha os cotovelos levemente dobrados durante o movimento.',
  safety_scapular_retraction_band: 'Movimento lento e controlado. Mantenha os ombros afastados das orelhas.',

  exercise_tricep_extension_band: 'Extensão de tríceps com faixa',
  instruction_tricep_extension_band: 'Em pé, pise na faixa com um pé. Segure a extremidade livre e leve o cotovelo para cima (dobrado ao lado da cabeça). Estenda o braço para cima contraindo o tríceps. Retorne lentamente. Alterne os braços.',
  safety_tricep_extension_band: 'Mantenha o cotovelo apontando para o teto durante o movimento. Use tensão de faixa adequada.',

  exercise_floor_push_ups: 'Flexão no chão',
  instruction_floor_push_ups: 'Em posição de prancha, com as mãos apoiadas no chão na largura dos ombros, desça o peito em direção ao chão dobrando os cotovelos. Empurre para cima para retornar. Pode ser feito com os joelhos apoiados se necessário.',
  safety_floor_push_ups: 'Mantenha o corpo alinhado da cabeça aos calcanhares (ou joelhos). Não bloqueie os cotovelos ao estender.',

  exercise_front_plank: 'Prancha frontal',
  instruction_front_plank: 'Apoie os antebraços e as pontas dos pés no chão. Mantenha o corpo em linha reta da cabeça aos calcanhares com o abdômen contraído. Respire normalmente enquanto mantém a posição.',
  safety_front_plank: 'Se for muito difícil, apoie os joelhos. Não deixe o quadril cair nem elevá-lo demais.',

  exercise_side_plank_knee: 'Prancha lateral (joelho apoiado)',
  instruction_side_plank_knee: 'Deitado de lado, apoie o antebraço no chão e o joelho inferior dobrado como suporte. Eleve o quadril formando uma linha reta do joelho ao ombro. Mantenha a posição. Troque de lado.',
  safety_side_plank_knee: 'Alinhe o cotovelo abaixo do ombro. Mantenha o abdômen contraído e respire normalmente.',

  exercise_slow_mountain_climber: 'Escalador lento',
  instruction_slow_mountain_climber: 'Em posição de prancha alta (mãos no chão), leve lentamente um joelho em direção ao peito e volte a estendê-lo. Alterne as pernas de forma controlada, sem elevar o quadril.',
  safety_slow_mountain_climber: 'Mantenha as costas retas e o abdômen contraído. Mova-se devagar para não perder o equilíbrio.',

  exercise_foot_taps_directions: 'Toques em múltiplas direções',
  instruction_foot_taps_directions: 'Apoiado em uma cadeira, toque com o pé direito em diferentes direções: à frente, lateral e atrás. Repita com o pé esquerdo. Mantenha o equilíbrio sobre o pé de apoio.',
  safety_foot_taps_directions: 'Segure bem na cadeira. Comece com amplitudes pequenas e aumente progressivamente.',

  exercise_lateral_shuffle: 'Deslocamento lateral rápido',
  instruction_lateral_shuffle: 'Com os joelhos levemente dobrados e o tronco levemente inclinado à frente, dê passos rápidos para a direita e depois para a esquerda, arrastando o pé traseiro antes do próximo passo.',
  safety_lateral_shuffle: 'Limpe o espaço de obstáculos. Use calçado antiderrapante. Reduza a velocidade se sentir instabilidade.',

  exercise_step_touch: 'Toque lateral (Step Touch)',
  instruction_step_touch: 'Dê um passo para a direita com o pé direito e toque o chão com o pé esquerdo ao lado. Repita para a esquerda. Mantenha um ritmo constante e os braços em movimento sincronizado.',
  safety_step_touch: 'Verifique o espaço dos lados. Reduza a amplitude do passo se sentir desequilíbrio.',
};